// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill_v2.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const backfillExercisesForSkill = `-- name: BackfillExercisesForSkill :execrows
UPDATE exercises
SET item_id = $2, mode = 0, correct_answer = $3
WHERE skill_id = $1 AND item_id IS NULL
`

type BackfillExercisesForSkillParams struct {
	SkillID       uuid.UUID
	ItemID        *uuid.UUID
	CorrectAnswer pgtype.Text
}

// Attach item_id/mode/correct_answer to every still-unmapped exercise row
// for one legacy skill. correct_answer is the skill's own key: exercises.
// skill_id is always the exercise's TARGET (correct) skill, so the correct
// answer key never varies per exercise the way a review's chosen/correct
// key can.
func (q *Queries) BackfillExercisesForSkill(ctx context.Context, arg BackfillExercisesForSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillExercisesForSkill, arg.SkillID, arg.ItemID, arg.CorrectAnswer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const backfillReviewsForSkill = `-- name: BackfillReviewsForSkill :execrows
UPDATE reviews
SET item_id = $2, mode = 0, chosen = chosen_key, correct_answer = correct_key
WHERE skill_id = $1 AND item_id IS NULL
`

type BackfillReviewsForSkillParams struct {
	SkillID uuid.UUID
	ItemID  *uuid.UUID
}

// Attach item_id/mode/chosen/correct_answer to every still-unmapped review
// row for one legacy skill. chosen/correct_answer are copied from each
// review's own chosen_key/correct_key (a wrong answer's chosen_key differs
// from correct_key), unlike exercises' fixed per-skill correct_answer.
func (q *Queries) BackfillReviewsForSkill(ctx context.Context, arg BackfillReviewsForSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillReviewsForSkill, arg.SkillID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countIntroductionsForItem = `-- name: CountIntroductionsForItem :one
SELECT count(*) FROM introductions WHERE user_id = $1 AND item_id = $2
`

type CountIntroductionsForItemParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

// Whether any introduction row (of any outcome) already exists for a
// user+item — the "if none exists" guard before synthesizing one
// (architecture §3.5).
func (q *Queries) CountIntroductionsForItem(ctx context.Context, arg CountIntroductionsForItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntroductionsForItem, arg.UserID, arg.ItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSynthesizedIntroduction = `-- name: InsertSynthesizedIntroduction :exec
INSERT INTO introductions (user_id, item_id, seq, outcome, shown_at, answered_at)
VALUES ($1, $2, 1, 0, $3, $3)
`

type InsertSynthesizedIntroductionParams struct {
	UserID  uuid.UUID
	ItemID  uuid.UUID
	ShownAt pgtype.Timestamptz
}

// One synthesized first-exposure introduction row for a migrated user_item:
// seq=1, outcome=0 (got_it), shown_at=answered_at=introduced_at (architecture
// §3.5) — satisfies the "already introduced" invariant so migrated items are
// never re-introduced.
func (q *Queries) InsertSynthesizedIntroduction(ctx context.Context, arg InsertSynthesizedIntroductionParams) error {
	_, err := q.db.Exec(ctx, insertSynthesizedIntroduction, arg.UserID, arg.ItemID, arg.ShownAt)
	return err
}

const insertUserItemIfAbsent = `-- name: InsertUserItemIfAbsent :execrows
INSERT INTO user_items (
  user_id, item_id, lifecycle, due, stability, difficulty, reps, lapses,
  state, last_review, introduced_at, known_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NULL
)
ON CONFLICT (user_id, item_id) DO NOTHING
`

type InsertUserItemIfAbsentParams struct {
	UserID       uuid.UUID
	ItemID       uuid.UUID
	Lifecycle    int16
	Due          pgtype.Timestamptz
	Stability    float64
	Difficulty   float64
	Reps         int32
	Lapses       int32
	State        int16
	LastReview   pgtype.Timestamptz
	IntroducedAt pgtype.Timestamptz
}

// Backfill-only insert: unlike PutUserItem's ON CONFLICT DO UPDATE (the
// live app's upsert), this is ON CONFLICT DO NOTHING so a re-run of
// -backfill-v2 never clobbers a user_items row the live app (or a prior
// backfill run) already created. Returns the number of rows actually
// inserted (0 or 1) so the caller knows whether this pair is newly migrated.
func (q *Queries) InsertUserItemIfAbsent(ctx context.Context, arg InsertUserItemIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserItemIfAbsent,
		arg.UserID,
		arg.ItemID,
		arg.Lifecycle,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
		arg.IntroducedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllUserSkills = `-- name: ListAllUserSkills :many

SELECT user_id, skill_id, due, stability, difficulty, reps, lapses, state, last_review FROM user_skills ORDER BY user_id, skill_id
`

// Queries for cmd/ingest's -backfill-v2 mode (architecture §3.4/§3.5, task
// W4.1): maps legacy skills/user_skills/exercises/reviews onto the v2
// topics/items/user_items/introductions framework, in the same database.
// All additive — no schema change, just new queries against existing
// 000001-000006 tables.
// Every user_skills row across all users — the source rows -backfill-v2
// maps into user_items (there is no existing "list all" query; every other
// user_skills reader is scoped to one user).
func (q *Queries) ListAllUserSkills(ctx context.Context) ([]UserSkill, error) {
	rows, err := q.db.Query(ctx, listAllUserSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSkill{}
	for rows.Next() {
		var i UserSkill
		if err := rows.Scan(
			&i.UserID,
			&i.SkillID,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
