// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDueSkills = `-- name: CountDueSkills :one
SELECT count(*) FROM user_skills
WHERE user_id = $1 AND due <= $2
`

type CountDueSkillsParams struct {
	UserID uuid.UUID
	Due    pgtype.Timestamptz
}

func (q *Queries) CountDueSkills(ctx context.Context, arg CountDueSkillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDueSkills, arg.UserID, arg.Due)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCard = `-- name: GetCard :one
SELECT due, stability, difficulty, reps, lapses, state, last_review
FROM user_skills
WHERE user_id = $1 AND skill_id = $2
`

type GetCardParams struct {
	UserID  uuid.UUID
	SkillID uuid.UUID
}

type GetCardRow struct {
	Due        pgtype.Timestamptz
	Stability  float64
	Difficulty float64
	Reps       int32
	Lapses     int32
	State      int16
	LastReview pgtype.Timestamptz
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (GetCardRow, error) {
	row := q.db.QueryRow(ctx, getCard, arg.UserID, arg.SkillID)
	var i GetCardRow
	err := row.Scan(
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
	)
	return i, err
}

const listCardsForUser = `-- name: ListCardsForUser :many
SELECT due, stability, difficulty, reps, lapses, state, last_review
FROM user_skills
WHERE user_id = $1
`

type ListCardsForUserRow struct {
	Due        pgtype.Timestamptz
	Stability  float64
	Difficulty float64
	Reps       int32
	Lapses     int32
	State      int16
	LastReview pgtype.Timestamptz
}

func (q *Queries) ListCardsForUser(ctx context.Context, userID uuid.UUID) ([]ListCardsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsForUserRow{}
	for rows.Next() {
		var i ListCardsForUserRow
		if err := rows.Scan(
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCard = `-- name: PutCard :exec
INSERT INTO user_skills (user_id, skill_id, due, stability, difficulty, reps, lapses, state, last_review)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, skill_id)
DO UPDATE SET
  due = EXCLUDED.due,
  stability = EXCLUDED.stability,
  difficulty = EXCLUDED.difficulty,
  reps = EXCLUDED.reps,
  lapses = EXCLUDED.lapses,
  state = EXCLUDED.state,
  last_review = EXCLUDED.last_review
`

type PutCardParams struct {
	UserID     uuid.UUID
	SkillID    uuid.UUID
	Due        pgtype.Timestamptz
	Stability  float64
	Difficulty float64
	Reps       int32
	Lapses     int32
	State      int16
	LastReview pgtype.Timestamptz
}

func (q *Queries) PutCard(ctx context.Context, arg PutCardParams) error {
	_, err := q.db.Exec(ctx, putCard,
		arg.UserID,
		arg.SkillID,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
	)
	return err
}
