// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countContentByKey = `-- name: CountContentByKey :one
SELECT count(*) FROM content_items WHERE kind = $1 AND key = $2
`

type CountContentByKeyParams struct {
	Kind string
	Key  string
}

func (q *Queries) CountContentByKey(ctx context.Context, arg CountContentByKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContentByKey, arg.Kind, arg.Key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT ci.id, ci.kind, ci.key, ci.payload, ci.source, ci.char_length
FROM content_items ci
WHERE ci.id = $1
`

type GetContentByIDRow struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

func (q *Queries) GetContentByID(ctx context.Context, id uuid.UUID) (GetContentByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i GetContentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Key,
		&i.Payload,
		&i.Source,
		&i.CharLength,
	)
	return i, err
}

const getContentByKindKey = `-- name: GetContentByKindKey :one
SELECT ci.id, ci.kind, ci.key, ci.payload, ci.source, ci.char_length
FROM content_items ci
WHERE ci.kind = $1 AND ci.key = $2
LIMIT 1
`

type GetContentByKindKeyParams struct {
	Kind string
	Key  string
}

type GetContentByKindKeyRow struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

// internal/study's bridge content row: exact (kind,key) lookup, unlike
// SampleContent/SampleContentAny which are hardcoded to kind='sentence' and
// pick randomly among multiple rows.
func (q *Queries) GetContentByKindKey(ctx context.Context, arg GetContentByKindKeyParams) (GetContentByKindKeyRow, error) {
	row := q.db.QueryRow(ctx, getContentByKindKey, arg.Kind, arg.Key)
	var i GetContentByKindKeyRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Key,
		&i.Payload,
		&i.Source,
		&i.CharLength,
	)
	return i, err
}

const insertContent = `-- name: InsertContent :exec
INSERT INTO content_items (kind, key, payload, source, char_length)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind, key, payload) DO NOTHING
`

type InsertContentParams struct {
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

func (q *Queries) InsertContent(ctx context.Context, arg InsertContentParams) error {
	_, err := q.db.Exec(ctx, insertContent,
		arg.Kind,
		arg.Key,
		arg.Payload,
		arg.Source,
		arg.CharLength,
	)
	return err
}

const sampleContent = `-- name: SampleContent :one
SELECT ci.id, ci.kind, ci.key, ci.payload, ci.source, ci.char_length
FROM content_items ci
WHERE ci.kind = 'sentence' AND ci.key = $1
  AND ci.id NOT IN (
    SELECT r.content_id
    FROM reviews r
    WHERE r.user_id = $2 AND r.correct_answer = $1 AND r.content_id IS NOT NULL
    ORDER BY r.reviewed_at DESC
    LIMIT 50
  )
ORDER BY random()
LIMIT 1
`

type SampleContentParams struct {
	Key    string
	UserID uuid.UUID
}

type SampleContentRow struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

// Random sentence for an item key, excluding the user's last-50 seen content
// for that key (recently-seen exclusion, contract §4).
func (q *Queries) SampleContent(ctx context.Context, arg SampleContentParams) (SampleContentRow, error) {
	row := q.db.QueryRow(ctx, sampleContent, arg.Key, arg.UserID)
	var i SampleContentRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Key,
		&i.Payload,
		&i.Source,
		&i.CharLength,
	)
	return i, err
}

const sampleContentAny = `-- name: SampleContentAny :one
SELECT ci.id, ci.kind, ci.key, ci.payload, ci.source, ci.char_length
FROM content_items ci
WHERE ci.kind = 'sentence' AND ci.key = $1
ORDER BY random()
LIMIT 1
`

type SampleContentAnyRow struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

// Fallback sampler with no exclusion (used when the pool is smaller than the
// exclusion window).
func (q *Queries) SampleContentAny(ctx context.Context, key string) (SampleContentAnyRow, error) {
	row := q.db.QueryRow(ctx, sampleContentAny, key)
	var i SampleContentAnyRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Key,
		&i.Payload,
		&i.Source,
		&i.CharLength,
	)
	return i, err
}
