// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at FROM countries WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id uuid.UUID) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.IsoA2,
		&i.IsoA3,
		&i.NumericCode,
		&i.Name,
		&i.OfficialName,
		&i.FlagEmoji,
		&i.ParentCountryID,
		&i.IsSubdivision,
		&i.UnMember,
		&i.GgCoverage,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryByISO = `-- name: GetCountryByISO :one
SELECT id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at FROM countries WHERE iso_a2 = $1
`

func (q *Queries) GetCountryByISO(ctx context.Context, isoA2 pgtype.Text) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByISO, isoA2)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.IsoA2,
		&i.IsoA3,
		&i.NumericCode,
		&i.Name,
		&i.OfficialName,
		&i.FlagEmoji,
		&i.ParentCountryID,
		&i.IsSubdivision,
		&i.UnMember,
		&i.GgCoverage,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryByISOA3 = `-- name: GetCountryByISOA3 :one
SELECT id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at FROM countries WHERE iso_a3 = $1
`

func (q *Queries) GetCountryByISOA3(ctx context.Context, isoA3 pgtype.Text) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByISOA3, isoA3)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.IsoA2,
		&i.IsoA3,
		&i.NumericCode,
		&i.Name,
		&i.OfficialName,
		&i.FlagEmoji,
		&i.ParentCountryID,
		&i.IsSubdivision,
		&i.UnMember,
		&i.GgCoverage,
		&i.CreatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at FROM countries ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.IsoA2,
			&i.IsoA3,
			&i.NumericCode,
			&i.Name,
			&i.OfficialName,
			&i.FlagEmoji,
			&i.ParentCountryID,
			&i.IsSubdivision,
			&i.UnMember,
			&i.GgCoverage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountriesByFlags = `-- name: ListCountriesByFlags :many
SELECT id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at FROM countries WHERE un_member = $1 AND gg_coverage = $2 ORDER BY name
`

type ListCountriesByFlagsParams struct {
	UnMember   bool
	GgCoverage bool
}

// Filter by the first-class un_member/gg_coverage booleans (e.g. the
// road-side audit's "every gg_coverage country" check).
func (q *Queries) ListCountriesByFlags(ctx context.Context, arg ListCountriesByFlagsParams) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountriesByFlags, arg.UnMember, arg.GgCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.IsoA2,
			&i.IsoA3,
			&i.NumericCode,
			&i.Name,
			&i.OfficialName,
			&i.FlagEmoji,
			&i.ParentCountryID,
			&i.IsSubdivision,
			&i.UnMember,
			&i.GgCoverage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCountry = `-- name: UpsertCountry :one
INSERT INTO countries (
  iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji,
  parent_country_id, is_subdivision, un_member, gg_coverage
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (iso_a2) DO UPDATE SET
  iso_a3 = EXCLUDED.iso_a3,
  numeric_code = EXCLUDED.numeric_code,
  name = EXCLUDED.name,
  official_name = EXCLUDED.official_name,
  flag_emoji = EXCLUDED.flag_emoji,
  parent_country_id = EXCLUDED.parent_country_id,
  is_subdivision = EXCLUDED.is_subdivision,
  un_member = EXCLUDED.un_member,
  gg_coverage = EXCLUDED.gg_coverage
RETURNING id, iso_a2, iso_a3, numeric_code, name, official_name, flag_emoji, parent_country_id, is_subdivision, un_member, gg_coverage, created_at
`

type UpsertCountryParams struct {
	IsoA2           pgtype.Text
	IsoA3           pgtype.Text
	NumericCode     pgtype.Text
	Name            string
	OfficialName    pgtype.Text
	FlagEmoji       pgtype.Text
	ParentCountryID *uuid.UUID
	IsSubdivision   bool
	UnMember        bool
	GgCoverage      bool
}

// Keyed on iso_a2. NOTE: rows with iso_a2 IS NULL (subdivisions without an
// alpha-2 code) never conflict and always insert a new row — acceptable for
// now; subdivision seeding dedups by a caller-side lookup (GetCountryByISO on
// iso_a3, or a future dedicated key) before calling this.
func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, upsertCountry,
		arg.IsoA2,
		arg.IsoA3,
		arg.NumericCode,
		arg.Name,
		arg.OfficialName,
		arg.FlagEmoji,
		arg.ParentCountryID,
		arg.IsSubdivision,
		arg.UnMember,
		arg.GgCoverage,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.IsoA2,
		&i.IsoA3,
		&i.NumericCode,
		&i.Name,
		&i.OfficialName,
		&i.FlagEmoji,
		&i.ParentCountryID,
		&i.IsSubdivision,
		&i.UnMember,
		&i.GgCoverage,
		&i.CreatedAt,
	)
	return i, err
}
