// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledDecks = `-- name: CountEnabledDecks :one
SELECT count(*) FROM user_decks WHERE user_id = $1 AND enabled = true
`

func (q *Queries) CountEnabledDecks(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledDecks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeckBySlug = `-- name: GetDeckBySlug :one
SELECT id, slug, name, exercise_type, created_at FROM decks WHERE slug = $1
`

func (q *Queries) GetDeckBySlug(ctx context.Context, slug string) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckBySlug, slug)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ExerciseType,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, deck_id, key, label FROM skills WHERE id = $1
`

func (q *Queries) GetSkillByID(ctx context.Context, id uuid.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Key,
		&i.Label,
	)
	return i, err
}

const listAllSkills = `-- name: ListAllSkills :many
SELECT id, deck_id, key, label FROM skills ORDER BY deck_id, key
`

func (q *Queries) ListAllSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Key,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecks = `-- name: ListDecks :many
SELECT id, slug, name, exercise_type, created_at FROM decks ORDER BY created_at, slug
`

func (q *Queries) ListDecks(ctx context.Context) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ExerciseType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSkillCards = `-- name: ListEnabledSkillCards :many
SELECT s.id AS skill_id, s.deck_id, s.key, s.label,
       us.due, us.stability, us.difficulty, us.reps, us.lapses, us.state, us.last_review
FROM skills s
JOIN decks d ON d.id = s.deck_id
JOIN user_decks ud ON ud.deck_id = d.id AND ud.user_id = $1 AND ud.enabled = true
LEFT JOIN user_skills us ON us.skill_id = s.id AND us.user_id = $1
ORDER BY s.deck_id, s.key
`

type ListEnabledSkillCardsRow struct {
	SkillID    uuid.UUID
	DeckID     uuid.UUID
	Key        string
	Label      string
	Due        pgtype.Timestamptz
	Stability  pgtype.Float8
	Difficulty pgtype.Float8
	Reps       pgtype.Int4
	Lapses     pgtype.Int4
	State      pgtype.Int2
	LastReview pgtype.Timestamptz
}

func (q *Queries) ListEnabledSkillCards(ctx context.Context, userID uuid.UUID) ([]ListEnabledSkillCardsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledSkillCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledSkillCardsRow{}
	for rows.Next() {
		var i ListEnabledSkillCardsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.DeckID,
			&i.Key,
			&i.Label,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSkills = `-- name: ListEnabledSkills :many
SELECT s.id AS skill_id, s.deck_id, s.key, s.label
FROM skills s
JOIN decks d ON d.id = s.deck_id
JOIN user_decks ud ON ud.deck_id = d.id AND ud.user_id = $1 AND ud.enabled = true
ORDER BY s.deck_id, s.key
`

type ListEnabledSkillsRow struct {
	SkillID uuid.UUID
	DeckID  uuid.UUID
	Key     string
	Label   string
}

func (q *Queries) ListEnabledSkills(ctx context.Context, userID uuid.UUID) ([]ListEnabledSkillsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledSkillsRow{}
	for rows.Next() {
		var i ListEnabledSkillsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.DeckID,
			&i.Key,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByDeck = `-- name: ListSkillsByDeck :many
SELECT id, deck_id, key, label FROM skills WHERE deck_id = $1 ORDER BY key
`

func (q *Queries) ListSkillsByDeck(ctx context.Context, deckID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Key,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDecks = `-- name: ListUserDecks :many
SELECT d.id, d.slug, d.name, d.exercise_type, d.created_at,
       COALESCE(ud.enabled, false) AS enabled
FROM decks d
LEFT JOIN user_decks ud ON ud.deck_id = d.id AND ud.user_id = $1
ORDER BY d.created_at, d.slug
`

type ListUserDecksRow struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	ExerciseType string
	CreatedAt    pgtype.Timestamptz
	Enabled      bool
}

func (q *Queries) ListUserDecks(ctx context.Context, userID uuid.UUID) ([]ListUserDecksRow, error) {
	rows, err := q.db.Query(ctx, listUserDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDecksRow{}
	for rows.Next() {
		var i ListUserDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ExerciseType,
			&i.CreatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDeckEnabled = `-- name: SetUserDeckEnabled :exec
INSERT INTO user_decks (user_id, deck_id, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, deck_id)
DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetUserDeckEnabledParams struct {
	UserID  uuid.UUID
	DeckID  uuid.UUID
	Enabled bool
}

func (q *Queries) SetUserDeckEnabled(ctx context.Context, arg SetUserDeckEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserDeckEnabled, arg.UserID, arg.DeckID, arg.Enabled)
	return err
}

const upsertDeck = `-- name: UpsertDeck :one
INSERT INTO decks (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, slug, name, exercise_type, created_at
`

type UpsertDeckParams struct {
	Slug string
	Name string
}

func (q *Queries) UpsertDeck(ctx context.Context, arg UpsertDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, upsertDeck, arg.Slug, arg.Name)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ExerciseType,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (deck_id, key, label)
VALUES ($1, $2, $3)
ON CONFLICT (deck_id, key)
DO UPDATE SET label = EXCLUDED.label
RETURNING id, deck_id, key, label
`

type UpsertSkillParams struct {
	DeckID uuid.UUID
	Key    string
	Label  string
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill, arg.DeckID, arg.Key, arg.Label)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Key,
		&i.Label,
	)
	return i, err
}
