// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOpenExercisesByTopic = `-- name: DeleteOpenExercisesByTopic :execrows
DELETE FROM exercises e
USING items i
WHERE e.item_id = i.id AND i.topic_id = $1 AND e.answered_at IS NULL
`

// Delete only the OPEN (unanswered) exercises of every item under a topic —
// the cities cutover's reset. Answered exercises stay as archive (reviews
// reference only answered exercises, so this never trips the reviews->exercises
// FK), and items themselves are untouched (exercises->items has no cascade).
func (q *Queries) DeleteOpenExercisesByTopic(ctx context.Context, topicID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOpenExercisesByTopic, topicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, user_id, item_id, content_id, mode, prompt, options, correct_answer, is_media, practice, created_at, answered_at, message_id FROM exercises WHERE id = $1
`

// internal/study.Service.Answer: fetch one exercise by id with the full
// mode-aware column set.
func (q *Queries) GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.ContentID,
		&i.Mode,
		&i.Prompt,
		&i.Options,
		&i.CorrectAnswer,
		&i.IsMedia,
		&i.Practice,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const getExercisesByItem = `-- name: GetExercisesByItem :many
SELECT id, user_id, content_id, item_id, mode, prompt, options,
       correct_answer, is_media, practice, created_at, answered_at, message_id
FROM exercises
WHERE item_id = $1
ORDER BY created_at DESC
`

type GetExercisesByItemRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ContentID     *uuid.UUID
	ItemID        uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
	CreatedAt     pgtype.Timestamptz
	AnsweredAt    pgtype.Timestamptz
	MessageID     pgtype.Int8
}

func (q *Queries) GetExercisesByItem(ctx context.Context, itemID uuid.UUID) ([]GetExercisesByItemRow, error) {
	rows, err := q.db.Query(ctx, getExercisesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExercisesByItemRow{}
	for rows.Next() {
		var i GetExercisesByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ContentID,
			&i.ItemID,
			&i.Mode,
			&i.Prompt,
			&i.Options,
			&i.CorrectAnswer,
			&i.IsMedia,
			&i.Practice,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenExerciseByMode = `-- name: GetOpenExerciseByMode :one
SELECT id, user_id, content_id, item_id, mode, prompt, options,
       correct_answer, is_media, practice, created_at, answered_at, message_id
FROM exercises
WHERE user_id = $1 AND mode = $2 AND answered_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenExerciseByModeParams struct {
	UserID uuid.UUID
	Mode   int16
}

type GetOpenExerciseByModeRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ContentID     *uuid.UUID
	ItemID        uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
	CreatedAt     pgtype.Timestamptz
	AnsweredAt    pgtype.Timestamptz
	MessageID     pgtype.Int8
}

// Latest open exercise of a given mode for a user (architecture §5.4: free-text
// answers arrive as a plain message, resolved via the caller's single open
// mode=text exercise).
func (q *Queries) GetOpenExerciseByMode(ctx context.Context, arg GetOpenExerciseByModeParams) (GetOpenExerciseByModeRow, error) {
	row := q.db.QueryRow(ctx, getOpenExerciseByMode, arg.UserID, arg.Mode)
	var i GetOpenExerciseByModeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContentID,
		&i.ItemID,
		&i.Mode,
		&i.Prompt,
		&i.Options,
		&i.CorrectAnswer,
		&i.IsMedia,
		&i.Practice,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :one
INSERT INTO exercises (user_id, item_id, content_id, mode, prompt, options, correct_answer, is_media, practice)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type InsertExerciseParams struct {
	UserID        uuid.UUID
	ItemID        uuid.UUID
	ContentID     *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
}

type InsertExerciseRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

// internal/study.Service: insert a mode-aware exercise row — item_id/mode/
// prompt/options/correct_answer/is_media/practice — in one shot. content_id
// is optional (shared/topic-scoped content, or none).
func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (InsertExerciseRow, error) {
	row := q.db.QueryRow(ctx, insertExercise,
		arg.UserID,
		arg.ItemID,
		arg.ContentID,
		arg.Mode,
		arg.Prompt,
		arg.Options,
		arg.CorrectAnswer,
		arg.IsMedia,
		arg.Practice,
	)
	var i InsertExerciseRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const markExerciseAnswered = `-- name: MarkExerciseAnswered :one
UPDATE exercises
SET answered_at = $2
WHERE id = $1 AND answered_at IS NULL
RETURNING id
`

type MarkExerciseAnsweredParams struct {
	ID         uuid.UUID
	AnsweredAt pgtype.Timestamptz
}

// Single-use answer guard: flips answered_at only if still open. A returned row
// means this caller owns the answer; no row means it was already answered.
func (q *Queries) MarkExerciseAnswered(ctx context.Context, arg MarkExerciseAnsweredParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markExerciseAnswered, arg.ID, arg.AnsweredAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setExerciseItemFields = `-- name: SetExerciseItemFields :exec
UPDATE exercises
SET item_id = $2, mode = $3, prompt = $4, correct_answer = $5, is_media = $6, practice = $7
WHERE id = $1
`

type SetExerciseItemFieldsParams struct {
	ID            uuid.UUID
	ItemID        uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
}

// Updates item/mode-aware metadata on an existing exercise row.
func (q *Queries) SetExerciseItemFields(ctx context.Context, arg SetExerciseItemFieldsParams) error {
	_, err := q.db.Exec(ctx, setExerciseItemFields,
		arg.ID,
		arg.ItemID,
		arg.Mode,
		arg.Prompt,
		arg.CorrectAnswer,
		arg.IsMedia,
		arg.Practice,
	)
	return err
}

const setExerciseMessageID = `-- name: SetExerciseMessageID :exec
UPDATE exercises SET message_id = $2 WHERE id = $1
`

type SetExerciseMessageIDParams struct {
	ID        uuid.UUID
	MessageID pgtype.Int8
}

func (q *Queries) SetExerciseMessageID(ctx context.Context, arg SetExerciseMessageIDParams) error {
	_, err := q.db.Exec(ctx, setExerciseMessageID, arg.ID, arg.MessageID)
	return err
}
