// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExercise = `-- name: GetExercise :one
SELECT id, user_id, skill_id, content_id, options, created_at, answered_at, message_id
FROM exercises
WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.ContentID,
		&i.Options,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :one
INSERT INTO exercises (user_id, skill_id, content_id, options)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertExerciseParams struct {
	UserID    uuid.UUID
	SkillID   uuid.UUID
	ContentID uuid.UUID
	Options   []byte
}

type InsertExerciseRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (InsertExerciseRow, error) {
	row := q.db.QueryRow(ctx, insertExercise,
		arg.UserID,
		arg.SkillID,
		arg.ContentID,
		arg.Options,
	)
	var i InsertExerciseRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const markExerciseAnswered = `-- name: MarkExerciseAnswered :one
UPDATE exercises
SET answered_at = $2
WHERE id = $1 AND answered_at IS NULL
RETURNING id
`

type MarkExerciseAnsweredParams struct {
	ID         uuid.UUID
	AnsweredAt pgtype.Timestamptz
}

// Single-use answer guard: flips answered_at only if still open. A returned row
// means this caller owns the answer; no row means it was already answered.
func (q *Queries) MarkExerciseAnswered(ctx context.Context, arg MarkExerciseAnsweredParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markExerciseAnswered, arg.ID, arg.AnsweredAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setExerciseMessageID = `-- name: SetExerciseMessageID :exec
UPDATE exercises SET message_id = $2 WHERE id = $1
`

type SetExerciseMessageIDParams struct {
	ID        uuid.UUID
	MessageID pgtype.Int8
}

func (q *Queries) SetExerciseMessageID(ctx context.Context, arg SetExerciseMessageIDParams) error {
	_, err := q.db.Exec(ctx, setExerciseMessageID, arg.ID, arg.MessageID)
	return err
}
