// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExercise = `-- name: GetExercise :one
SELECT id, user_id, skill_id, content_id, options, created_at, answered_at, message_id
FROM exercises
WHERE id = $1
`

type GetExerciseRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SkillID    uuid.UUID
	ContentID  uuid.UUID
	Options    []byte
	CreatedAt  pgtype.Timestamptz
	AnsweredAt pgtype.Timestamptz
	MessageID  pgtype.Int8
}

func (q *Queries) GetExercise(ctx context.Context, id uuid.UUID) (GetExerciseRow, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i GetExerciseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.ContentID,
		&i.Options,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const getExerciseByIDV2 = `-- name: GetExerciseByIDV2 :one
SELECT id, user_id, skill_id, content_id, options, created_at, answered_at, message_id, item_id, mode, prompt, correct_answer, is_media, practice FROM exercises WHERE id = $1
`

// v2 (internal/study.Service.AnswerV2): fetch one exercise by id with the
// full mode-aware column set (unlike the legacy GetExercise, which predates
// item_id/mode/prompt/correct_answer/is_media/practice).
func (q *Queries) GetExerciseByIDV2(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByIDV2, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.ContentID,
		&i.Options,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
		&i.ItemID,
		&i.Mode,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.IsMedia,
		&i.Practice,
	)
	return i, err
}

const getExercisesByItem = `-- name: GetExercisesByItem :many
SELECT id, user_id, skill_id, content_id, item_id, mode, prompt, options,
       correct_answer, is_media, practice, created_at, answered_at, message_id
FROM exercises
WHERE item_id = $1
ORDER BY created_at DESC
`

type GetExercisesByItemRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SkillID       uuid.UUID
	ContentID     uuid.UUID
	ItemID        *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
	CreatedAt     pgtype.Timestamptz
	AnsweredAt    pgtype.Timestamptz
	MessageID     pgtype.Int8
}

func (q *Queries) GetExercisesByItem(ctx context.Context, itemID *uuid.UUID) ([]GetExercisesByItemRow, error) {
	rows, err := q.db.Query(ctx, getExercisesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExercisesByItemRow{}
	for rows.Next() {
		var i GetExercisesByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillID,
			&i.ContentID,
			&i.ItemID,
			&i.Mode,
			&i.Prompt,
			&i.Options,
			&i.CorrectAnswer,
			&i.IsMedia,
			&i.Practice,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenExerciseByMode = `-- name: GetOpenExerciseByMode :one
SELECT id, user_id, skill_id, content_id, item_id, mode, prompt, options,
       correct_answer, is_media, practice, created_at, answered_at, message_id
FROM exercises
WHERE user_id = $1 AND mode = $2 AND answered_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenExerciseByModeParams struct {
	UserID uuid.UUID
	Mode   int16
}

type GetOpenExerciseByModeRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SkillID       uuid.UUID
	ContentID     uuid.UUID
	ItemID        *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
	CreatedAt     pgtype.Timestamptz
	AnsweredAt    pgtype.Timestamptz
	MessageID     pgtype.Int8
}

// Latest open exercise of a given mode for a user (architecture §5.4: free-text
// answers arrive as a plain message, resolved via the caller's single open
// mode=text exercise).
func (q *Queries) GetOpenExerciseByMode(ctx context.Context, arg GetOpenExerciseByModeParams) (GetOpenExerciseByModeRow, error) {
	row := q.db.QueryRow(ctx, getOpenExerciseByMode, arg.UserID, arg.Mode)
	var i GetOpenExerciseByModeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.ContentID,
		&i.ItemID,
		&i.Mode,
		&i.Prompt,
		&i.Options,
		&i.CorrectAnswer,
		&i.IsMedia,
		&i.Practice,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :one
INSERT INTO exercises (user_id, skill_id, content_id, options)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertExerciseParams struct {
	UserID    uuid.UUID
	SkillID   uuid.UUID
	ContentID uuid.UUID
	Options   []byte
}

type InsertExerciseRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (InsertExerciseRow, error) {
	row := q.db.QueryRow(ctx, insertExercise,
		arg.UserID,
		arg.SkillID,
		arg.ContentID,
		arg.Options,
	)
	var i InsertExerciseRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertExerciseV2 = `-- name: InsertExerciseV2 :one
INSERT INTO exercises (user_id, skill_id, content_id, item_id, mode, prompt, options, correct_answer, is_media, practice)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at
`

type InsertExerciseV2Params struct {
	UserID        uuid.UUID
	SkillID       uuid.UUID
	ContentID     uuid.UUID
	ItemID        *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	Options       []byte
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
}

type InsertExerciseV2Row struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

// v2 (internal/study.Service): insert a mode-aware exercise row directly —
// item_id/mode/prompt/options/correct_answer/is_media/practice — in one
// shot, instead of the legacy two-step InsertExercise+SetExerciseItemFields
// path. skill_id/content_id are still NOT NULL (dropped only by a later
// migration out of this wave's scope); callers without a natural skill/
// content row supply a bridge placeholder (see internal/study's bridge.go).
func (q *Queries) InsertExerciseV2(ctx context.Context, arg InsertExerciseV2Params) (InsertExerciseV2Row, error) {
	row := q.db.QueryRow(ctx, insertExerciseV2,
		arg.UserID,
		arg.SkillID,
		arg.ContentID,
		arg.ItemID,
		arg.Mode,
		arg.Prompt,
		arg.Options,
		arg.CorrectAnswer,
		arg.IsMedia,
		arg.Practice,
	)
	var i InsertExerciseV2Row
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const markExerciseAnswered = `-- name: MarkExerciseAnswered :one
UPDATE exercises
SET answered_at = $2
WHERE id = $1 AND answered_at IS NULL
RETURNING id
`

type MarkExerciseAnsweredParams struct {
	ID         uuid.UUID
	AnsweredAt pgtype.Timestamptz
}

// Single-use answer guard: flips answered_at only if still open. A returned row
// means this caller owns the answer; no row means it was already answered.
func (q *Queries) MarkExerciseAnswered(ctx context.Context, arg MarkExerciseAnsweredParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markExerciseAnswered, arg.ID, arg.AnsweredAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setExerciseItemFields = `-- name: SetExerciseItemFields :exec
UPDATE exercises
SET item_id = $2, mode = $3, prompt = $4, correct_answer = $5, is_media = $6, practice = $7
WHERE id = $1
`

type SetExerciseItemFieldsParams struct {
	ID            uuid.UUID
	ItemID        *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
}

// v2: attach item/mode-aware metadata (architecture §2.5) to an exercise row.
// item_id stays nullable until the old-quiz migration backfills it (§3.1).
func (q *Queries) SetExerciseItemFields(ctx context.Context, arg SetExerciseItemFieldsParams) error {
	_, err := q.db.Exec(ctx, setExerciseItemFields,
		arg.ID,
		arg.ItemID,
		arg.Mode,
		arg.Prompt,
		arg.CorrectAnswer,
		arg.IsMedia,
		arg.Practice,
	)
	return err
}

const setExerciseMessageID = `-- name: SetExerciseMessageID :exec
UPDATE exercises SET message_id = $2 WHERE id = $1
`

type SetExerciseMessageIDParams struct {
	ID        uuid.UUID
	MessageID pgtype.Int8
}

func (q *Queries) SetExerciseMessageID(ctx context.Context, arg SetExerciseMessageIDParams) error {
	_, err := q.db.Exec(ctx, setExerciseMessageID, arg.ID, arg.MessageID)
	return err
}
