// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCountryFactsByDef = `-- name: DeleteCountryFactsByDef :exec
DELETE FROM country_facts WHERE country_id = $1 AND fact_def_id = $2
`

type DeleteCountryFactsByDefParams struct {
	CountryID uuid.UUID
	FactDefID uuid.UUID
}

// Clears every fact value for one country+def (used to replace multi-valued
// facts wholesale on reseed).
func (q *Queries) DeleteCountryFactsByDef(ctx context.Context, arg DeleteCountryFactsByDefParams) error {
	_, err := q.db.Exec(ctx, deleteCountryFactsByDef, arg.CountryID, arg.FactDefID)
	return err
}

const getFactDefByKey = `-- name: GetFactDefByKey :one
SELECT id, key, label, value_type, unit, cardinality, dataset, created_at FROM fact_defs WHERE key = $1
`

func (q *Queries) GetFactDefByKey(ctx context.Context, key string) (FactDef, error) {
	row := q.db.QueryRow(ctx, getFactDefByKey, key)
	var i FactDef
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.ValueType,
		&i.Unit,
		&i.Cardinality,
		&i.Dataset,
		&i.CreatedAt,
	)
	return i, err
}

const insertCountryFact = `-- name: InsertCountryFact :one
INSERT INTO country_facts (country_id, fact_def_id, val_text, val_num, val_bool, source, observed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, country_id, fact_def_id, val_text, val_num, val_bool, source, observed_at, created_at
`

type InsertCountryFactParams struct {
	CountryID  uuid.UUID
	FactDefID  uuid.UUID
	ValText    pgtype.Text
	ValNum     pgtype.Float8
	ValBool    pgtype.Bool
	Source     pgtype.Text
	ObservedAt pgtype.Date
}

// Typed insert: the caller sets exactly one of val_text/val_num/val_bool (the
// CHECK constraint enforces it); the other two are passed as NULL.
func (q *Queries) InsertCountryFact(ctx context.Context, arg InsertCountryFactParams) (CountryFact, error) {
	row := q.db.QueryRow(ctx, insertCountryFact,
		arg.CountryID,
		arg.FactDefID,
		arg.ValText,
		arg.ValNum,
		arg.ValBool,
		arg.Source,
		arg.ObservedAt,
	)
	var i CountryFact
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.FactDefID,
		&i.ValText,
		&i.ValNum,
		&i.ValBool,
		&i.Source,
		&i.ObservedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCountryFactsByDefKey = `-- name: ListCountryFactsByDefKey :many
SELECT cf.id, cf.country_id, cf.fact_def_id, cf.val_text, cf.val_num, cf.val_bool, cf.source, cf.observed_at, cf.created_at
FROM country_facts cf
JOIN fact_defs fd ON fd.id = cf.fact_def_id
WHERE fd.key = $1
ORDER BY cf.country_id
`

// Facts for one fact_def, looked up by its key (e.g. 'drives_on') — the
// building block for arbitrary-filter joins (architecture §2.7).
func (q *Queries) ListCountryFactsByDefKey(ctx context.Context, key string) ([]CountryFact, error) {
	rows, err := q.db.Query(ctx, listCountryFactsByDefKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryFact{}
	for rows.Next() {
		var i CountryFact
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.FactDefID,
			&i.ValText,
			&i.ValNum,
			&i.ValBool,
			&i.Source,
			&i.ObservedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactDefs = `-- name: ListFactDefs :many
SELECT id, key, label, value_type, unit, cardinality, dataset, created_at FROM fact_defs ORDER BY key
`

func (q *Queries) ListFactDefs(ctx context.Context) ([]FactDef, error) {
	rows, err := q.db.Query(ctx, listFactDefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FactDef{}
	for rows.Next() {
		var i FactDef
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.ValueType,
			&i.Unit,
			&i.Cardinality,
			&i.Dataset,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsForCountry = `-- name: ListFactsForCountry :many
SELECT cf.id, cf.country_id, cf.fact_def_id, fd.key AS fact_key, cf.val_text,
       cf.val_num, cf.val_bool, cf.source, cf.observed_at, cf.created_at
FROM country_facts cf
JOIN fact_defs fd ON fd.id = cf.fact_def_id
WHERE cf.country_id = $1
ORDER BY fd.key
`

type ListFactsForCountryRow struct {
	ID         uuid.UUID
	CountryID  uuid.UUID
	FactDefID  uuid.UUID
	FactKey    string
	ValText    pgtype.Text
	ValNum     pgtype.Float8
	ValBool    pgtype.Bool
	Source     pgtype.Text
	ObservedAt pgtype.Date
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListFactsForCountry(ctx context.Context, countryID uuid.UUID) ([]ListFactsForCountryRow, error) {
	rows, err := q.db.Query(ctx, listFactsForCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFactsForCountryRow{}
	for rows.Next() {
		var i ListFactsForCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.FactDefID,
			&i.FactKey,
			&i.ValText,
			&i.ValNum,
			&i.ValBool,
			&i.Source,
			&i.ObservedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFactDef = `-- name: UpsertFactDef :one
INSERT INTO fact_defs (key, label, value_type, unit, cardinality, dataset)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  value_type = EXCLUDED.value_type,
  unit = EXCLUDED.unit,
  cardinality = EXCLUDED.cardinality,
  dataset = EXCLUDED.dataset
RETURNING id, key, label, value_type, unit, cardinality, dataset, created_at
`

type UpsertFactDefParams struct {
	Key         string
	Label       string
	ValueType   string
	Unit        pgtype.Text
	Cardinality string
	Dataset     pgtype.Text
}

func (q *Queries) UpsertFactDef(ctx context.Context, arg UpsertFactDefParams) (FactDef, error) {
	row := q.db.QueryRow(ctx, upsertFactDef,
		arg.Key,
		arg.Label,
		arg.ValueType,
		arg.Unit,
		arg.Cardinality,
		arg.Dataset,
	)
	var i FactDef
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.ValueType,
		&i.Unit,
		&i.Cardinality,
		&i.Dataset,
		&i.CreatedAt,
	)
	return i, err
}
