// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGameStats = `-- name: GetGameStats :one
SELECT user_id, game, best_streak, runs, last_played_at FROM game_stats WHERE user_id = $1 AND game = $2
`

type GetGameStatsParams struct {
	UserID uuid.UUID
	Game   string
}

func (q *Queries) GetGameStats(ctx context.Context, arg GetGameStatsParams) (GameStat, error) {
	row := q.db.QueryRow(ctx, getGameStats, arg.UserID, arg.Game)
	var i GameStat
	err := row.Scan(
		&i.UserID,
		&i.Game,
		&i.BestStreak,
		&i.Runs,
		&i.LastPlayedAt,
	)
	return i, err
}

const upsertGameRun = `-- name: UpsertGameRun :one
INSERT INTO game_stats (user_id, game, best_streak, runs, last_played_at)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (user_id, game) DO UPDATE SET
  best_streak = GREATEST(game_stats.best_streak, EXCLUDED.best_streak),
  runs = game_stats.runs + 1,
  last_played_at = EXCLUDED.last_played_at
RETURNING user_id, game, best_streak, runs, last_played_at
`

type UpsertGameRunParams struct {
	UserID       uuid.UUID
	Game         string
	BestStreak   int32
	LastPlayedAt pgtype.Timestamptz
}

// Records the end of one game-zone run (design doc "Persistence"):
// best_streak only ever grows (GREATEST against the existing row), runs
// increments by one, and last_played_at is stamped to when the run ended.
// No per-run log — reviews stays FSRS-only; run state (streak, open
// answer, used content ids) lives in-memory per chat in the telegram layer.
func (q *Queries) UpsertGameRun(ctx context.Context, arg UpsertGameRunParams) (GameStat, error) {
	row := q.db.QueryRow(ctx, upsertGameRun,
		arg.UserID,
		arg.Game,
		arg.BestStreak,
		arg.LastPlayedAt,
	)
	var i GameStat
	err := row.Scan(
		&i.UserID,
		&i.Game,
		&i.BestStreak,
		&i.Runs,
		&i.LastPlayedAt,
	)
	return i, err
}
