// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: introductions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerIntroduction = `-- name: AnswerIntroduction :one
UPDATE introductions SET outcome = $2, answered_at = $3 WHERE id = $1 RETURNING id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id
`

type AnswerIntroductionParams struct {
	ID         uuid.UUID
	Outcome    pgtype.Int2
	AnsweredAt pgtype.Timestamptz
}

func (q *Queries) AnswerIntroduction(ctx context.Context, arg AnswerIntroductionParams) (Introduction, error) {
	row := q.db.QueryRow(ctx, answerIntroduction, arg.ID, arg.Outcome, arg.AnsweredAt)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const answerIntroductionOnce = `-- name: AnswerIntroductionOnce :one
UPDATE introductions
SET outcome = $2, answered_at = $3
WHERE id = $1 AND answered_at IS NULL
RETURNING id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id
`

type AnswerIntroductionOnceParams struct {
	ID         uuid.UUID
	Outcome    pgtype.Int2
	AnsweredAt pgtype.Timestamptz
}

// Single-use answer guard for introductions (mirrors MarkExerciseAnswered):
// flips outcome/answered_at only if still open. A returned row means this
// caller owns the answer; no row means it was already answered (a stale
// second tap on the same intro card, architecture §5.1/§5.5).
func (q *Queries) AnswerIntroductionOnce(ctx context.Context, arg AnswerIntroductionOnceParams) (Introduction, error) {
	row := q.db.QueryRow(ctx, answerIntroductionOnce, arg.ID, arg.Outcome, arg.AnsweredAt)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const countIntroductionsToday = `-- name: CountIntroductionsToday :one
SELECT count(DISTINCT item_id) FROM introductions
WHERE user_id = $1 AND seq = 1 AND outcome IS NOT NULL AND outcome != 1
  AND answered_at >= $2 AND answered_at < $3
`

type CountIntroductionsTodayParams struct {
	UserID       uuid.UUID
	AnsweredAt   pgtype.Timestamptz
	AnsweredAt_2 pgtype.Timestamptz
}

// "Introduced today" for the daily budget (architecture §2.4): distinct items
// with a first-exposure (seq=1), a genuinely-introduced outcome, inside the
// caller-supplied local-day [from, to) bounds. Excludes outcome=1
// (engram.IntroKnown, "I know this"): that outcome never actually introduces
// the item, so it must not spend the daily intro budget.
func (q *Queries) CountIntroductionsToday(ctx context.Context, arg CountIntroductionsTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntroductionsToday, arg.UserID, arg.AnsweredAt, arg.AnsweredAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOpenIntroductionsByTopic = `-- name: DeleteOpenIntroductionsByTopic :execrows
DELETE FROM introductions x
USING items i
WHERE x.item_id = i.id AND i.topic_id = $1 AND x.answered_at IS NULL
`

// Delete only the OPEN (unanswered) introduction cards of every item under a
// topic — the cities cutover's reset drops stale, still-on-screen intro cards
// for the renamed topic. Answered introductions stay as archive; items are
// untouched.
func (q *Queries) DeleteOpenIntroductionsByTopic(ctx context.Context, topicID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOpenIntroductionsByTopic, topicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntroductionByID = `-- name: GetIntroductionByID :one
SELECT id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id FROM introductions WHERE id = $1
`

// internal/study.Service.AnswerIntro: resolve the item an introduction
// callback refers to.
func (q *Queries) GetIntroductionByID(ctx context.Context, id uuid.UUID) (Introduction, error) {
	row := q.db.QueryRow(ctx, getIntroductionByID, id)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const getLatestOpenIntroduction = `-- name: GetLatestOpenIntroduction :one
SELECT id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id FROM introductions
WHERE user_id = $1 AND answered_at IS NULL
ORDER BY shown_at DESC
LIMIT 1
`

// Latest open (shown, not yet answered) introduction for a user, regardless
// of item — used to resolve a bare callback/reply to the card still on screen.
func (q *Queries) GetLatestOpenIntroduction(ctx context.Context, userID uuid.UUID) (Introduction, error) {
	row := q.db.QueryRow(ctx, getLatestOpenIntroduction, userID)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const getLatestOpenIntroductionForItem = `-- name: GetLatestOpenIntroductionForItem :one
SELECT id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id FROM introductions
WHERE user_id = $1 AND item_id = $2 AND answered_at IS NULL
ORDER BY shown_at DESC
LIMIT 1
`

type GetLatestOpenIntroductionForItemParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) GetLatestOpenIntroductionForItem(ctx context.Context, arg GetLatestOpenIntroductionForItemParams) (Introduction, error) {
	row := q.db.QueryRow(ctx, getLatestOpenIntroductionForItem, arg.UserID, arg.ItemID)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const insertIntroduction = `-- name: InsertIntroduction :one
INSERT INTO introductions (user_id, item_id, seq, outcome, shown_at, answered_at, message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, item_id, seq, outcome, shown_at, answered_at, message_id
`

type InsertIntroductionParams struct {
	UserID     uuid.UUID
	ItemID     uuid.UUID
	Seq        int32
	Outcome    pgtype.Int2
	ShownAt    pgtype.Timestamptz
	AnsweredAt pgtype.Timestamptz
	MessageID  pgtype.Int8
}

func (q *Queries) InsertIntroduction(ctx context.Context, arg InsertIntroductionParams) (Introduction, error) {
	row := q.db.QueryRow(ctx, insertIntroduction,
		arg.UserID,
		arg.ItemID,
		arg.Seq,
		arg.Outcome,
		arg.ShownAt,
		arg.AnsweredAt,
		arg.MessageID,
	)
	var i Introduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Seq,
		&i.Outcome,
		&i.ShownAt,
		&i.AnsweredAt,
		&i.MessageID,
	)
	return i, err
}

const nextIntroSeq = `-- name: NextIntroSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM introductions WHERE user_id = $1 AND item_id = $2
`

type NextIntroSeqParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

// seq for the next introduction row of this user+item (1 = first exposure,
// >1 = re-view, architecture §2.4).
func (q *Queries) NextIntroSeq(ctx context.Context, arg NextIntroSeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextIntroSeq, arg.UserID, arg.ItemID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setIntroductionMessageID = `-- name: SetIntroductionMessageID :exec
UPDATE introductions SET message_id = $2 WHERE id = $1
`

type SetIntroductionMessageIDParams struct {
	ID        uuid.UUID
	MessageID pgtype.Int8
}

func (q *Queries) SetIntroductionMessageID(ctx context.Context, arg SetIntroductionMessageIDParams) error {
	_, err := q.db.Exec(ctx, setIntroductionMessageID, arg.ID, arg.MessageID)
	return err
}
