// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getItemByID = `-- name: GetItemByID :one
SELECT id, topic_id, key, label, tier, payload, country_id, position, active, created_at FROM items WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Key,
		&i.Label,
		&i.Tier,
		&i.Payload,
		&i.CountryID,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getItemEffectiveTier = `-- name: GetItemEffectiveTier :one
SELECT tier FROM item_tiers WHERE item_id = $1
`

func (q *Queries) GetItemEffectiveTier(ctx context.Context, itemID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, getItemEffectiveTier, itemID)
	var tier int16
	err := row.Scan(&tier)
	return tier, err
}

const listActiveItemsByTopic = `-- name: ListActiveItemsByTopic :many
SELECT id, topic_id, key, label, tier, payload, country_id, position, active, created_at FROM items WHERE topic_id = $1 AND active = true ORDER BY position, key
`

func (q *Queries) ListActiveItemsByTopic(ctx context.Context, topicID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listActiveItemsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Key,
			&i.Label,
			&i.Tier,
			&i.Payload,
			&i.CountryID,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllItemKeyLabels = `-- name: ListAllItemKeyLabels :many
SELECT key, label FROM items
`

type ListAllItemKeyLabelsRow struct {
	Key   string
	Label string
}

// Global key->label lookup for confusion display. Best-effort: item keys
// are only unique WITHIN a topic (items' UNIQUE (topic_id, key) constraint),
// so a key shared by two topics resolves to whichever row this query
// returns last for it — an acceptable approximation for a "which
// language/character/word" hint.
func (q *Queries) ListAllItemKeyLabels(ctx context.Context) ([]ListAllItemKeyLabelsRow, error) {
	rows, err := q.db.Query(ctx, listAllItemKeyLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllItemKeyLabelsRow{}
	for rows.Next() {
		var i ListAllItemKeyLabelsRow
		if err := rows.Scan(&i.Key, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByTopic = `-- name: ListItemsByTopic :many
SELECT id, topic_id, key, label, tier, payload, country_id, position, active, created_at FROM items WHERE topic_id = $1 ORDER BY position, key
`

func (q *Queries) ListItemsByTopic(ctx context.Context, topicID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Key,
			&i.Label,
			&i.Tier,
			&i.Payload,
			&i.CountryID,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsWithTierByTopic = `-- name: ListItemsWithTierByTopic :many
SELECT i.id, i.topic_id, i.key, i.label, i.tier, i.payload, i.country_id,
       i.position, i.active, i.created_at, it.tier AS effective_tier
FROM items i
JOIN item_tiers it ON it.item_id = i.id
WHERE i.topic_id = $1
ORDER BY i.position, i.key
`

type ListItemsWithTierByTopicRow struct {
	ID            uuid.UUID
	TopicID       uuid.UUID
	Key           string
	Label         string
	Tier          pgtype.Int2
	Payload       []byte
	CountryID     *uuid.UUID
	Position      int32
	Active        bool
	CreatedAt     pgtype.Timestamptz
	EffectiveTier int16
}

// Items for a topic with their effective tier (COALESCE(items.tier,
// topics.base_tier)) resolved via the item_tiers view.
func (q *Queries) ListItemsWithTierByTopic(ctx context.Context, topicID uuid.UUID) ([]ListItemsWithTierByTopicRow, error) {
	rows, err := q.db.Query(ctx, listItemsWithTierByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsWithTierByTopicRow{}
	for rows.Next() {
		var i ListItemsWithTierByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Key,
			&i.Label,
			&i.Tier,
			&i.Payload,
			&i.CountryID,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
			&i.EffectiveTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (topic_id, key, label, tier, payload, country_id, position, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (topic_id, key)
DO UPDATE SET
  label = EXCLUDED.label,
  tier = EXCLUDED.tier,
  payload = EXCLUDED.payload,
  country_id = EXCLUDED.country_id,
  position = EXCLUDED.position,
  active = EXCLUDED.active
RETURNING id, topic_id, key, label, tier, payload, country_id, position, active, created_at
`

type UpsertItemParams struct {
	TopicID   uuid.UUID
	Key       string
	Label     string
	Tier      pgtype.Int2
	Payload   []byte
	CountryID *uuid.UUID
	Position  int32
	Active    bool
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, upsertItem,
		arg.TopicID,
		arg.Key,
		arg.Label,
		arg.Tier,
		arg.Payload,
		arg.CountryID,
		arg.Position,
		arg.Active,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Key,
		&i.Label,
		&i.Tier,
		&i.Payload,
		&i.CountryID,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
