// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMediaByContentID = `-- name: GetMediaByContentID :one
SELECT id, content_id, local_path, sha256, telegram_file_id, width, height, bytes, created_at FROM media_files WHERE content_id = $1
`

func (q *Queries) GetMediaByContentID(ctx context.Context, contentID *uuid.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaByContentID, contentID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.LocalPath,
		&i.Sha256,
		&i.TelegramFileID,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByLocalPath = `-- name: GetMediaByLocalPath :one
SELECT id, content_id, local_path, sha256, telegram_file_id, width, height, bytes, created_at FROM media_files WHERE local_path = $1
`

func (q *Queries) GetMediaByLocalPath(ctx context.Context, localPath string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaByLocalPath, localPath)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.LocalPath,
		&i.Sha256,
		&i.TelegramFileID,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
	)
	return i, err
}

const putMediaFile = `-- name: PutMediaFile :one
INSERT INTO media_files (content_id, local_path, sha256, telegram_file_id, width, height, bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (local_path) DO UPDATE SET
  content_id = EXCLUDED.content_id,
  sha256 = EXCLUDED.sha256,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  bytes = EXCLUDED.bytes
RETURNING id, content_id, local_path, sha256, telegram_file_id, width, height, bytes, created_at
`

type PutMediaFileParams struct {
	ContentID      *uuid.UUID
	LocalPath      string
	Sha256         pgtype.Text
	TelegramFileID pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	Bytes          pgtype.Int4
}

// Upsert keyed on local_path (the stable identity of a media asset on disk).
func (q *Queries) PutMediaFile(ctx context.Context, arg PutMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, putMediaFile,
		arg.ContentID,
		arg.LocalPath,
		arg.Sha256,
		arg.TelegramFileID,
		arg.Width,
		arg.Height,
		arg.Bytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.LocalPath,
		&i.Sha256,
		&i.TelegramFileID,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.CreatedAt,
	)
	return i, err
}

const setMediaTelegramFileID = `-- name: SetMediaTelegramFileID :exec
UPDATE media_files SET telegram_file_id = $2 WHERE id = $1
`

type SetMediaTelegramFileIDParams struct {
	ID             uuid.UUID
	TelegramFileID pgtype.Text
}

// Caches the Telegram file_id after first upload so later sends can reuse it
// and skip re-uploading the asset (architecture §2.8, decision 6).
func (q *Queries) SetMediaTelegramFileID(ctx context.Context, arg SetMediaTelegramFileIDParams) error {
	_, err := q.db.Exec(ctx, setMediaTelegramFileID, arg.ID, arg.TelegramFileID)
	return err
}
