// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentItem struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
	TopicID    *uuid.UUID
}

type Country struct {
	ID              uuid.UUID
	IsoA2           pgtype.Text
	IsoA3           pgtype.Text
	NumericCode     pgtype.Text
	Name            string
	OfficialName    pgtype.Text
	FlagEmoji       pgtype.Text
	ParentCountryID *uuid.UUID
	IsSubdivision   bool
	UnMember        bool
	GgCoverage      bool
	CreatedAt       pgtype.Timestamptz
}

type CountryFact struct {
	ID         uuid.UUID
	CountryID  uuid.UUID
	FactDefID  uuid.UUID
	ValText    pgtype.Text
	ValNum     pgtype.Float8
	ValBool    pgtype.Bool
	Source     pgtype.Text
	ObservedAt pgtype.Date
	CreatedAt  pgtype.Timestamptz
}

type Deck struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	ExerciseType string
	CreatedAt    pgtype.Timestamptz
}

type Exercise struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	SkillID       uuid.UUID
	ContentID     uuid.UUID
	Options       []byte
	CreatedAt     pgtype.Timestamptz
	AnsweredAt    pgtype.Timestamptz
	MessageID     pgtype.Int8
	ItemID        *uuid.UUID
	Mode          int16
	Prompt        pgtype.Text
	CorrectAnswer pgtype.Text
	IsMedia       bool
	Practice      bool
}

type FactDef struct {
	ID          uuid.UUID
	Key         string
	Label       string
	ValueType   string
	Unit        pgtype.Text
	Cardinality string
	Dataset     pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Introduction struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ItemID     uuid.UUID
	Seq        int32
	Outcome    pgtype.Int2
	ShownAt    pgtype.Timestamptz
	AnsweredAt pgtype.Timestamptz
	MessageID  pgtype.Int8
}

type Item struct {
	ID        uuid.UUID
	TopicID   uuid.UUID
	Key       string
	Label     string
	Tier      pgtype.Int2
	Payload   []byte
	CountryID *uuid.UUID
	Position  int32
	Active    bool
	CreatedAt pgtype.Timestamptz
}

type ItemTier struct {
	ItemID  uuid.UUID
	TopicID uuid.UUID
	Tier    int16
}

type MediaFile struct {
	ID             uuid.UUID
	ContentID      *uuid.UUID
	LocalPath      string
	Sha256         pgtype.Text
	TelegramFileID pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	Bytes          pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type Review struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	SkillID          uuid.UUID
	ExerciseID       *uuid.UUID
	ContentID        *uuid.UUID
	ChosenKey        string
	CorrectKey       string
	Correct          bool
	Rating           int16
	ResponseMs       pgtype.Int4
	StabilityBefore  float64
	DifficultyBefore float64
	StabilityAfter   float64
	DifficultyAfter  float64
	StateBefore      int16
	ScheduledDays    int32
	ElapsedDays      int32
	ReviewedAt       pgtype.Timestamptz
	Practice         bool
	ItemID           *uuid.UUID
	Mode             int16
	Chosen           pgtype.Text
	CorrectAnswer    pgtype.Text
}

type Skill struct {
	ID     uuid.UUID
	DeckID uuid.UUID
	Key    string
	Label  string
}

type Topic struct {
	ID            uuid.UUID
	ParentID      *uuid.UUID
	Slug          string
	Name          string
	Position      int32
	BaseTier      int16
	QuizKind      string
	ExerciseModes []string
	IsQuizzable   bool
	Config        []byte
	CreatedAt     pgtype.Timestamptz
}

type TopicPath struct {
	ID    uuid.UUID
	Path  string
	Depth int32
}

type User struct {
	ID               uuid.UUID
	TelegramID       int64
	Username         pgtype.Text
	DailyNewCap      int32
	RemindersEnabled bool
	Timezone         string
	CreatedAt        pgtype.Timestamptz
	LabelStyle       string
	ReminderHour     int32
	FollowUpEnabled  bool
	FollowUpDelayMin int32
	DailyIntroCap    int32
}

type UserDeck struct {
	UserID  uuid.UUID
	DeckID  uuid.UUID
	Enabled bool
}

type UserItem struct {
	UserID       uuid.UUID
	ItemID       uuid.UUID
	Lifecycle    int16
	Due          pgtype.Timestamptz
	Stability    float64
	Difficulty   float64
	Reps         int32
	Lapses       int32
	State        int16
	LastReview   pgtype.Timestamptz
	IntroducedAt pgtype.Timestamptz
	KnownAt      pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserSkill struct {
	UserID     uuid.UUID
	SkillID    uuid.UUID
	Due        pgtype.Timestamptz
	Stability  float64
	Difficulty float64
	Reps       int32
	Lapses     int32
	State      int16
	LastReview pgtype.Timestamptz
}

type UserTierProgress struct {
	UserID          uuid.UUID
	Tier            int16
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
	Complete        bool
	UpdatedAt       pgtype.Timestamptz
}

type UserTopic struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
	Enabled bool
}
