// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentItem struct {
	ID         uuid.UUID
	Kind       string
	Key        string
	Payload    string
	Source     string
	CharLength int32
}

type Deck struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	ExerciseType string
	CreatedAt    pgtype.Timestamptz
}

type Exercise struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SkillID    uuid.UUID
	ContentID  uuid.UUID
	Options    []byte
	CreatedAt  pgtype.Timestamptz
	AnsweredAt pgtype.Timestamptz
	MessageID  pgtype.Int8
}

type Review struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	SkillID          uuid.UUID
	ExerciseID       *uuid.UUID
	ContentID        *uuid.UUID
	ChosenKey        string
	CorrectKey       string
	Correct          bool
	Rating           int16
	ResponseMs       pgtype.Int4
	StabilityBefore  float64
	DifficultyBefore float64
	StabilityAfter   float64
	DifficultyAfter  float64
	StateBefore      int16
	ScheduledDays    int32
	ElapsedDays      int32
	ReviewedAt       pgtype.Timestamptz
	Practice         bool
}

type Skill struct {
	ID     uuid.UUID
	DeckID uuid.UUID
	Key    string
	Label  string
}

type User struct {
	ID               uuid.UUID
	TelegramID       int64
	Username         pgtype.Text
	DailyNewCap      int32
	RemindersEnabled bool
	Timezone         string
	CreatedAt        pgtype.Timestamptz
	LabelStyle       string
	ReminderHour     int32
	FollowUpEnabled  bool
	FollowUpDelayMin int32
}

type UserDeck struct {
	UserID  uuid.UUID
	DeckID  uuid.UUID
	Enabled bool
}

type UserSkill struct {
	UserID     uuid.UUID
	SkillID    uuid.UUID
	Due        pgtype.Timestamptz
	Stability  float64
	Difficulty float64
	Reps       int32
	Lapses     int32
	State      int16
	LastReview pgtype.Timestamptz
}
