// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AnswerIntroduction(ctx context.Context, arg AnswerIntroductionParams) (Introduction, error)
	// Single-use answer guard for introductions (mirrors MarkExerciseAnswered):
	// flips outcome/answered_at only if still open. A returned row means this
	// caller owns the answer; no row means it was already answered (a stale
	// second tap on the same intro card, architecture §5.1/§5.5).
	AnswerIntroductionOnce(ctx context.Context, arg AnswerIntroductionOnceParams) (Introduction, error)
	CountContentByKey(ctx context.Context, arg CountContentByKeyParams) (int64, error)
	// internal/study.Service.DueCount / the reminder loop's due count:
	// Introduced/Reviewing cards due at or before now.
	CountDueUserItems(ctx context.Context, arg CountDueUserItemsParams) (int64, error)
	// internal/study.Service.Stats, "introduced" count: items that have
	// left lifecycle=new (Introduced, Reviewing, or Known).
	CountIntroducedItems(ctx context.Context, userID uuid.UUID) (int64, error)
	// "Introduced today" for the daily budget (architecture §2.4): distinct items
	// with a first-exposure (seq=1), a genuinely-introduced outcome, inside the
	// caller-supplied local-day [from, to) bounds. Excludes outcome=1
	// (engram.IntroKnown, "I know this"): that outcome never actually introduces
	// the item, so it must not spend the daily intro budget.
	CountIntroductionsToday(ctx context.Context, arg CountIntroductionsTodayParams) (int64, error)
	// internal/study.Service.Stats, "known" count: items marked known via
	// the "I know this" intro outcome.
	CountKnownItems(ctx context.Context, userID uuid.UUID) (int64, error)
	CountReviewsSince(ctx context.Context, arg CountReviewsSinceParams) (int64, error)
	// Clears every fact value for one country+def (used to replace multi-valued
	// facts wholesale on reseed).
	DeleteCountryFactsByDef(ctx context.Context, arg DeleteCountryFactsByDefParams) error
	GetContentByID(ctx context.Context, id uuid.UUID) (GetContentByIDRow, error)
	// internal/study's bridge content row: exact (kind,key) lookup, unlike
	// SampleContent/SampleContentAny which are hardcoded to kind='sentence' and
	// pick randomly among multiple rows.
	GetContentByKindKey(ctx context.Context, arg GetContentByKindKeyParams) (GetContentByKindKeyRow, error)
	GetCountryByID(ctx context.Context, id uuid.UUID) (Country, error)
	GetCountryByISO(ctx context.Context, isoA2 pgtype.Text) (Country, error)
	GetCountryByISOA3(ctx context.Context, isoA3 pgtype.Text) (Country, error)
	// internal/study.Service.Answer: fetch one exercise by id with the full
	// mode-aware column set.
	GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetExercisesByItem(ctx context.Context, itemID uuid.UUID) ([]GetExercisesByItemRow, error)
	GetFactDefByKey(ctx context.Context, key string) (FactDef, error)
	GetGameStats(ctx context.Context, arg GetGameStatsParams) (GameStat, error)
	// internal/study.Service.AnswerIntro: resolve the item an introduction
	// callback refers to.
	GetIntroductionByID(ctx context.Context, id uuid.UUID) (Introduction, error)
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemEffectiveTier(ctx context.Context, itemID uuid.UUID) (int16, error)
	// Latest open (shown, not yet answered) introduction for a user, regardless
	// of item — used to resolve a bare callback/reply to the card still on screen.
	GetLatestOpenIntroduction(ctx context.Context, userID uuid.UUID) (Introduction, error)
	GetLatestOpenIntroductionForItem(ctx context.Context, arg GetLatestOpenIntroductionForItemParams) (Introduction, error)
	GetMediaByContentID(ctx context.Context, contentID *uuid.UUID) (MediaFile, error)
	GetMediaByLocalPath(ctx context.Context, localPath string) (MediaFile, error)
	// Latest open exercise of a given mode for a user (architecture §5.4: free-text
	// answers arrive as a plain message, resolved via the caller's single open
	// mode=text exercise).
	GetOpenExerciseByMode(ctx context.Context, arg GetOpenExerciseByModeParams) (GetOpenExerciseByModeRow, error)
	GetReviewsByItem(ctx context.Context, itemID uuid.UUID) ([]Review, error)
	GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error)
	// Path-walk helper: resolve a topic by its full slash-joined slug path (e.g.
	// "languages/special-characters"), via topic_paths.
	GetTopicByPath(ctx context.Context, path string) (Topic, error)
	// Path-walk helper: slash-joined slug path + depth from the recursive
	// topic_paths view, for one topic id.
	GetTopicPath(ctx context.Context, id uuid.UUID) (TopicPath, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	GetUserItem(ctx context.Context, arg GetUserItemParams) (UserItem, error)
	// internal/study.Service, the /topics enable/disable toggle: a single
	// topic's enabled flag for a user (default-on when no user_topics row
	// exists), for rendering the toggle's current state without listing every
	// topic (ListUserTopics).
	GetUserTopicEnabled(ctx context.Context, arg GetUserTopicEnabledParams) (bool, error)
	InsertContent(ctx context.Context, arg InsertContentParams) error
	// Typed insert: the caller sets exactly one of val_text/val_num/val_bool (the
	// CHECK constraint enforces it); the other two are passed as NULL.
	InsertCountryFact(ctx context.Context, arg InsertCountryFactParams) (CountryFact, error)
	// internal/study.Service: insert a mode-aware exercise row — item_id/mode/
	// prompt/options/correct_answer/is_media/practice — in one shot. content_id
	// is optional (shared/topic-scoped content, or none).
	InsertExercise(ctx context.Context, arg InsertExerciseParams) (InsertExerciseRow, error)
	InsertIntroduction(ctx context.Context, arg InsertIntroductionParams) (Introduction, error)
	// Append a review carrying the item-based, mode-aware column set
	// (architecture §2.5).
	InsertReview(ctx context.Context, arg InsertReviewParams) error
	ListActiveItemsByTopic(ctx context.Context, topicID uuid.UUID) ([]Item, error)
	// Global key->label lookup for confusion display. Best-effort: item keys
	// are only unique WITHIN a topic (items' UNIQUE (topic_id, key) constraint),
	// so a key shared by two topics resolves to whichever row this query
	// returns last for it — an acceptable approximation for a "which
	// language/character/word" hint.
	ListAllItemKeyLabels(ctx context.Context) ([]ListAllItemKeyLabelsRow, error)
	ListAllTopics(ctx context.Context) ([]Topic, error)
	// internal/study.Service.Stats: answer records for quiz.Confusion,
	// restricted to item-based attempts (item_id IS NOT NULL, so chosen/correct_answer
	// are always populated by the item-based write path — see internal/study's
	// finishAnswer).
	ListAttemptsSince(ctx context.Context, arg ListAttemptsSinceParams) ([]ListAttemptsSinceRow, error)
	// Candidate items for the introduction queue: active, tier-unlocked
	// (parameterized allowed-tiers array), and either no user_items row yet or
	// still lifecycle=new. Ordered tier, then topic position, then item position
	// — the app-supplied priority order engram.NextIntroductions preserves.
	ListCandidateIntroItems(ctx context.Context, arg ListCandidateIntroItemsParams) ([]ListCandidateIntroItemsRow, error)
	ListChildTopics(ctx context.Context, parentID *uuid.UUID) ([]Topic, error)
	ListCountries(ctx context.Context) ([]Country, error)
	// Filter by the first-class un_member/gg_coverage booleans (e.g. the
	// road-side audit's "every gg_coverage country" check).
	ListCountriesByFlags(ctx context.Context, arg ListCountriesByFlagsParams) ([]Country, error)
	// Facts for one fact_def, looked up by its key (e.g. 'drives_on') — the
	// building block for arbitrary-filter joins (architecture §2.7).
	ListCountryFactsByDefKey(ctx context.Context, key string) ([]CountryFact, error)
	// internal/study.TopicService: every effective tier used by an item
	// anywhere in a topic's subtree (itself + descendants) — the input to the
	// 🔒 AnyLocked/LockedTier badge (architecture §5.2), by comparing against
	// the user's currently-unlocked tier set.
	ListDistinctTiersUnderTopic(ctx context.Context, id uuid.UUID) ([]int16, error)
	// Due Introduced/Reviewing cards (engram.NextReview candidate set) joined
	// with their item for topic/key/label context.
	ListDueUserItems(ctx context.Context, arg ListDueUserItemsParams) ([]ListDueUserItemsRow, error)
	ListFactDefs(ctx context.Context) ([]FactDef, error)
	ListFactsForCountry(ctx context.Context, countryID uuid.UUID) ([]ListFactsForCountryRow, error)
	ListItemsByTopic(ctx context.Context, topicID uuid.UUID) ([]Item, error)
	// Items for a topic with their effective tier (COALESCE(items.tier,
	// topics.base_tier)) resolved via the item_tiers view.
	ListItemsWithTierByTopic(ctx context.Context, topicID uuid.UUID) ([]ListItemsWithTierByTopicRow, error)
	ListReviewsSince(ctx context.Context, arg ListReviewsSinceParams) ([]Review, error)
	ListRootTopics(ctx context.Context) ([]Topic, error)
	ListTierProgressForUser(ctx context.Context, userID uuid.UUID) ([]UserTierProgress, error)
	ListTopicPaths(ctx context.Context) ([]TopicPath, error)
	// internal/study.Service.Stats' DueForecast input: every Introduced/
	// Reviewing card for a user — replaces ListCardsForUser for the item-based review
	// path. Known/new rows are excluded: they carry a zeroed/absent due date
	// that would otherwise skew engram.DueForecast's "due today" bucket.
	ListUserItemCardsInFSRS(ctx context.Context, userID uuid.UUID) ([]UserItem, error)
	ListUserItemsByLifecycle(ctx context.Context, arg ListUserItemsByLifecycleParams) ([]UserItem, error)
	// Every topic with the user's enabled flag (default-on when no row exists,
	// per architecture §2.10 / §9 open question 5).
	ListUserTopics(ctx context.Context, userID uuid.UUID) ([]ListUserTopicsRow, error)
	// Single-use answer guard: flips answered_at only if still open. A returned row
	// means this caller owns the answer; no row means it was already answered.
	MarkExerciseAnswered(ctx context.Context, arg MarkExerciseAnsweredParams) (uuid.UUID, error)
	// seq for the next introduction row of this user+item (1 = first exposure,
	// >1 = re-view, architecture §2.4).
	NextIntroSeq(ctx context.Context, arg NextIntroSeqParams) (int32, error)
	// Upsert keyed on local_path (the stable identity of a media asset on disk).
	PutMediaFile(ctx context.Context, arg PutMediaFileParams) (MediaFile, error)
	// Upsert the lifecycle + FSRS card state for one user+item (engram.Lifecycle
	// and engram.CardState, architecture §2.3).
	PutUserItem(ctx context.Context, arg PutUserItemParams) error
	// On-the-fly source of truth for every tier of one user (architecture §4.2):
	// totals, introduced, and "good shape" counts via a single GROUP BY over
	// item_tiers <-> items <-> user_items. Good-shape = known (lifecycle=3) OR
	// graduated-and-durable (state=Review(2) AND stability>=21d, §4.1).
	RecomputeTierProgress(ctx context.Context, userID uuid.UUID) ([]RecomputeTierProgressRow, error)
	// Single-tier variant of RecomputeTierProgress, for the per-answer /
	// per-introduction transactional recompute (architecture §4.2/§5.5: "only the
	// item's tier needs recompute").
	RecomputeTierProgressForTier(ctx context.Context, arg RecomputeTierProgressForTierParams) (RecomputeTierProgressForTierRow, error)
	// internal/study.TopicService, architecture §5.2 TopicRow: aggregate
	// progress across an ENTIRE topic subtree (the topic itself plus every
	// descendant, via the topic_paths recursive view) for one user — a
	// container topic like "languages" rolls up every quizzable topic beneath
	// it (e.g. special-characters, guess-the-language/*, common-words) into one
	// total/introduced/good-shape line. Always returns exactly one row (zeros
	// when the subtree has no items).
	RecomputeTopicProgress(ctx context.Context, arg RecomputeTopicProgressParams) (RecomputeTopicProgressRow, error)
	// internal/study.TopicService, architecture §5.2 TierRow: per-tier
	// progress within ONE quizzable topic's OWN items (non-recursive — a
	// quizzable topic holds items directly, never a mix of items and child
	// topics), for one user.
	RecomputeTopicTierBreakdown(ctx context.Context, arg RecomputeTopicTierBreakdownParams) ([]RecomputeTopicTierBreakdownRow, error)
	// Re-parenting is a single-row UPDATE (architecture §2.1) — the tree is tiny,
	// so the topic_paths recursive view stays cheap even after this.
	ReparentTopic(ctx context.Context, arg ReparentTopicParams) error
	// internal/study.Service.Stats: per-topic accuracy since a time,
	// restricted to item-based attempts (item_id IS NOT NULL) — the /stats view.
	ReviewStatsByTopic(ctx context.Context, arg ReviewStatsByTopicParams) ([]ReviewStatsByTopicRow, error)
	// Random sentence for an item key, excluding the user's last-50 seen content
	// for that key (recently-seen exclusion, contract §4).
	SampleContent(ctx context.Context, arg SampleContentParams) (SampleContentRow, error)
	// Fallback sampler with no exclusion (used when the pool is smaller than the
	// exclusion window).
	SampleContentAny(ctx context.Context, key string) (SampleContentAnyRow, error)
	SetDailyCap(ctx context.Context, arg SetDailyCapParams) error
	// Updates item/mode-aware metadata on an existing exercise row.
	SetExerciseItemFields(ctx context.Context, arg SetExerciseItemFieldsParams) error
	SetExerciseMessageID(ctx context.Context, arg SetExerciseMessageIDParams) error
	SetFollowUpDelay(ctx context.Context, arg SetFollowUpDelayParams) error
	SetFollowUpEnabled(ctx context.Context, arg SetFollowUpEnabledParams) error
	// The /settings daily intro-cap row (architecture §2.10/§8 IntroCapStore).
	SetIntroCap(ctx context.Context, arg SetIntroCapParams) error
	SetIntroductionMessageID(ctx context.Context, arg SetIntroductionMessageIDParams) error
	SetLabelStyle(ctx context.Context, arg SetLabelStyleParams) error
	// Caches the Telegram file_id after first upload so later sends can reuse it
	// and skip re-uploading the asset (architecture §2.8, decision 6).
	SetMediaTelegramFileID(ctx context.Context, arg SetMediaTelegramFileIDParams) error
	SetReminderHour(ctx context.Context, arg SetReminderHourParams) error
	SetReminders(ctx context.Context, arg SetRemindersParams) error
	SetTimezone(ctx context.Context, arg SetTimezoneParams) error
	// ── user_topics (per-user topic opt-in/out, §2.10) ─────────────────────────
	SetUserTopicEnabled(ctx context.Context, arg SetUserTopicEnabledParams) error
	// Upsert a child topic (parent_id NOT NULL), keyed by the topics_sibling_slug
	// partial unique index.
	UpsertChildTopic(ctx context.Context, arg UpsertChildTopicParams) (Topic, error)
	// Keyed on iso_a2. NOTE: rows with iso_a2 IS NULL (subdivisions without an
	// alpha-2 code) never conflict and always insert a new row — acceptable for
	// now; subdivision seeding dedups by a caller-side lookup (GetCountryByISO on
	// iso_a3, or a future dedicated key) before calling this.
	UpsertCountry(ctx context.Context, arg UpsertCountryParams) (Country, error)
	UpsertFactDef(ctx context.Context, arg UpsertFactDefParams) (FactDef, error)
	// Records the end of one game-zone run (design doc "Persistence"):
	// best_streak only ever grows (GREATEST against the existing row), runs
	// increments by one, and last_played_at is stamped to when the run ended.
	// No per-run log — reviews stays FSRS-only; run state (streak, open
	// answer, used content ids) lives in-memory per chat in the telegram layer.
	UpsertGameRun(ctx context.Context, arg UpsertGameRunParams) (GameStat, error)
	UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error)
	// Upsert a root topic (parent_id IS NULL), keyed by the topics_root_slug
	// partial unique index.
	UpsertRootTopic(ctx context.Context, arg UpsertRootTopicParams) (Topic, error)
	UpsertTierProgress(ctx context.Context, arg UpsertTierProgressParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UsersWithReminders(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
