// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewsSince = `-- name: CountReviewsSince :one
SELECT count(*) FROM reviews r
LEFT JOIN items i ON i.id = r.item_id
JOIN users u ON u.id = $1
WHERE r.user_id = $1 AND r.reviewed_at >= $2
  AND (NOT u.gg_only OR i.gg_relevant)
`

type CountReviewsSinceParams struct {
	UserID     uuid.UUID
	ReviewedAt pgtype.Timestamptz
}

// GeoGuessr-only filtered (see ListReviewsSince).
func (q *Queries) CountReviewsSince(ctx context.Context, arg CountReviewsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsSince, arg.UserID, arg.ReviewedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewsByItem = `-- name: GetReviewsByItem :many
SELECT id, user_id, item_id, exercise_id, content_id, mode, chosen, correct_answer, correct, rating, response_ms, stability_before, difficulty_before, stability_after, difficulty_after, state_before, scheduled_days, elapsed_days, practice, reviewed_at FROM reviews WHERE item_id = $1 ORDER BY reviewed_at
`

func (q *Queries) GetReviewsByItem(ctx context.Context, itemID uuid.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.ExerciseID,
			&i.ContentID,
			&i.Mode,
			&i.Chosen,
			&i.CorrectAnswer,
			&i.Correct,
			&i.Rating,
			&i.ResponseMs,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.StabilityAfter,
			&i.DifficultyAfter,
			&i.StateBefore,
			&i.ScheduledDays,
			&i.ElapsedDays,
			&i.Practice,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReview = `-- name: InsertReview :exec
INSERT INTO reviews (
  user_id, item_id, exercise_id, content_id, mode, chosen, correct_answer,
  correct, rating, response_ms,
  stability_before, difficulty_before, stability_after, difficulty_after,
  state_before, scheduled_days, elapsed_days, practice, reviewed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13, $14,
  $15, $16, $17, $18, $19
)
`

type InsertReviewParams struct {
	UserID           uuid.UUID
	ItemID           uuid.UUID
	ExerciseID       *uuid.UUID
	ContentID        *uuid.UUID
	Mode             int16
	Chosen           pgtype.Text
	CorrectAnswer    pgtype.Text
	Correct          bool
	Rating           int16
	ResponseMs       pgtype.Int4
	StabilityBefore  float64
	DifficultyBefore float64
	StabilityAfter   float64
	DifficultyAfter  float64
	StateBefore      int16
	ScheduledDays    int32
	ElapsedDays      int32
	Practice         bool
	ReviewedAt       pgtype.Timestamptz
}

// Append a review carrying the item-based, mode-aware column set
// (architecture §2.5).
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) error {
	_, err := q.db.Exec(ctx, insertReview,
		arg.UserID,
		arg.ItemID,
		arg.ExerciseID,
		arg.ContentID,
		arg.Mode,
		arg.Chosen,
		arg.CorrectAnswer,
		arg.Correct,
		arg.Rating,
		arg.ResponseMs,
		arg.StabilityBefore,
		arg.DifficultyBefore,
		arg.StabilityAfter,
		arg.DifficultyAfter,
		arg.StateBefore,
		arg.ScheduledDays,
		arg.ElapsedDays,
		arg.Practice,
		arg.ReviewedAt,
	)
	return err
}

const listAttemptsSince = `-- name: ListAttemptsSince :many
SELECT r.correct_answer, r.chosen, r.correct, r.response_ms, r.reviewed_at
FROM reviews r
JOIN items i ON i.id = r.item_id
JOIN users u ON u.id = $1
WHERE r.user_id = $1 AND r.reviewed_at >= $2 AND r.item_id IS NOT NULL
  AND (NOT u.gg_only OR i.gg_relevant)
ORDER BY r.reviewed_at
`

type ListAttemptsSinceParams struct {
	UserID     uuid.UUID
	ReviewedAt pgtype.Timestamptz
}

type ListAttemptsSinceRow struct {
	CorrectAnswer pgtype.Text
	Chosen        pgtype.Text
	Correct       bool
	ResponseMs    pgtype.Int4
	ReviewedAt    pgtype.Timestamptz
}

// internal/study.Service.Stats: answer records for quiz.Confusion,
// restricted to item-based attempts (item_id IS NOT NULL, so chosen/correct_answer
// are always populated by the item-based write path — see internal/study's
// finishAnswer). GeoGuessr-only filtered (see ListReviewsSince).
func (q *Queries) ListAttemptsSince(ctx context.Context, arg ListAttemptsSinceParams) ([]ListAttemptsSinceRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsSince, arg.UserID, arg.ReviewedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsSinceRow{}
	for rows.Next() {
		var i ListAttemptsSinceRow
		if err := rows.Scan(
			&i.CorrectAnswer,
			&i.Chosen,
			&i.Correct,
			&i.ResponseMs,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsSince = `-- name: ListReviewsSince :many
SELECT r.id, r.user_id, r.item_id, r.exercise_id, r.content_id, r.mode, r.chosen, r.correct_answer, r.correct, r.rating, r.response_ms, r.stability_before, r.difficulty_before, r.stability_after, r.difficulty_after, r.state_before, r.scheduled_days, r.elapsed_days, r.practice, r.reviewed_at FROM reviews r
LEFT JOIN items i ON i.id = r.item_id
JOIN users u ON u.id = $1
WHERE r.user_id = $1 AND r.reviewed_at >= $2
  AND (NOT u.gg_only OR i.gg_relevant)
ORDER BY r.reviewed_at
`

type ListReviewsSinceParams struct {
	UserID     uuid.UUID
	ReviewedAt pgtype.Timestamptz
}

// GeoGuessr-only filter: LEFT JOIN items so legacy item-less rows are kept
// when gg_only is off, and dropped only under gg_only (a NULL gg_relevant
// fails the predicate) — the same no-extra-param, user_id-drives-the-flag
// pattern the study/tier queries use.
func (q *Queries) ListReviewsSince(ctx context.Context, arg ListReviewsSinceParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsSince, arg.UserID, arg.ReviewedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.ExerciseID,
			&i.ContentID,
			&i.Mode,
			&i.Chosen,
			&i.CorrectAnswer,
			&i.Correct,
			&i.Rating,
			&i.ResponseMs,
			&i.StabilityBefore,
			&i.DifficultyBefore,
			&i.StabilityAfter,
			&i.DifficultyAfter,
			&i.StateBefore,
			&i.ScheduledDays,
			&i.ElapsedDays,
			&i.Practice,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewStatsByTopic = `-- name: ReviewStatsByTopic :many
SELECT t.id AS topic_id, t.name,
       count(*) AS total,
       count(*) FILTER (WHERE r.correct) AS correct
FROM reviews r
JOIN items i ON i.id = r.item_id
JOIN topics t ON t.id = i.topic_id
JOIN users u ON u.id = $1
WHERE r.user_id = $1 AND r.reviewed_at >= $2 AND r.item_id IS NOT NULL
  AND (NOT u.gg_only OR i.gg_relevant)
GROUP BY t.id, t.name
ORDER BY t.name
`

type ReviewStatsByTopicParams struct {
	UserID     uuid.UUID
	ReviewedAt pgtype.Timestamptz
}

type ReviewStatsByTopicRow struct {
	TopicID uuid.UUID
	Name    string
	Total   int64
	Correct int64
}

// internal/study.Service.Stats: per-topic accuracy since a time,
// restricted to item-based attempts (item_id IS NOT NULL) — the /stats view.
// GeoGuessr-only filtered (see ListReviewsSince).
func (q *Queries) ReviewStatsByTopic(ctx context.Context, arg ReviewStatsByTopicParams) ([]ReviewStatsByTopicRow, error) {
	rows, err := q.db.Query(ctx, reviewStatsByTopic, arg.UserID, arg.ReviewedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewStatsByTopicRow{}
	for rows.Next() {
		var i ReviewStatsByTopicRow
		if err := rows.Scan(
			&i.TopicID,
			&i.Name,
			&i.Total,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
