// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tiers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listDistinctTiersUnderTopic = `-- name: ListDistinctTiersUnderTopic :many
WITH target AS (SELECT path FROM topic_paths WHERE topic_paths.id = $1)
SELECT DISTINCT it.tier
FROM items i
JOIN topic_paths tp ON tp.id = i.topic_id
JOIN item_tiers it ON it.item_id = i.id
CROSS JOIN target
WHERE tp.path = target.path OR tp.path LIKE target.path || '/%'
ORDER BY it.tier
`

// internal/study.TopicService: every effective tier used by an item
// anywhere in a topic's subtree (itself + descendants) — the input to the
// 🔒 AnyLocked/LockedTier badge (architecture §5.2), by comparing against
// the user's currently-unlocked tier set.
func (q *Queries) ListDistinctTiersUnderTopic(ctx context.Context, id uuid.UUID) ([]int16, error) {
	rows, err := q.db.Query(ctx, listDistinctTiersUnderTopic, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var tier int16
		if err := rows.Scan(&tier); err != nil {
			return nil, err
		}
		items = append(items, tier)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTierProgressForUser = `-- name: ListTierProgressForUser :many
SELECT user_id, tier, total_items, introduced_items, good_shape_items, complete, updated_at FROM user_tier_progress WHERE user_id = $1 ORDER BY tier
`

func (q *Queries) ListTierProgressForUser(ctx context.Context, userID uuid.UUID) ([]UserTierProgress, error) {
	rows, err := q.db.Query(ctx, listTierProgressForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTierProgress{}
	for rows.Next() {
		var i UserTierProgress
		if err := rows.Scan(
			&i.UserID,
			&i.Tier,
			&i.TotalItems,
			&i.IntroducedItems,
			&i.GoodShapeItems,
			&i.Complete,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeTierProgress = `-- name: RecomputeTierProgress :many
SELECT t.tier,
       count(*)::int AS total_items,
       count(*) FILTER (WHERE ui.lifecycle IS NOT NULL AND ui.lifecycle <> 0)::int AS introduced_items,
       count(*) FILTER (WHERE ui.lifecycle = 3
                           OR (ui.state = 2 AND ui.stability >= 21))::int AS good_shape_items
FROM item_tiers t
JOIN items i ON i.id = t.item_id
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = $1
GROUP BY t.tier
ORDER BY t.tier
`

type RecomputeTierProgressRow struct {
	Tier            int16
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
}

// On-the-fly source of truth for every tier of one user (architecture §4.2):
// totals, introduced, and "good shape" counts via a single GROUP BY over
// item_tiers <-> items <-> user_items. Good-shape = known (lifecycle=3) OR
// graduated-and-durable (state=Review(2) AND stability>=21d, §4.1).
func (q *Queries) RecomputeTierProgress(ctx context.Context, userID uuid.UUID) ([]RecomputeTierProgressRow, error) {
	rows, err := q.db.Query(ctx, recomputeTierProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecomputeTierProgressRow{}
	for rows.Next() {
		var i RecomputeTierProgressRow
		if err := rows.Scan(
			&i.Tier,
			&i.TotalItems,
			&i.IntroducedItems,
			&i.GoodShapeItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeTierProgressForTier = `-- name: RecomputeTierProgressForTier :one
SELECT t.tier,
       count(*)::int AS total_items,
       count(*) FILTER (WHERE ui.lifecycle IS NOT NULL AND ui.lifecycle <> 0)::int AS introduced_items,
       count(*) FILTER (WHERE ui.lifecycle = 3
                           OR (ui.state = 2 AND ui.stability >= 21))::int AS good_shape_items
FROM item_tiers t
JOIN items i ON i.id = t.item_id
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = $1
WHERE t.tier = $2
GROUP BY t.tier
`

type RecomputeTierProgressForTierParams struct {
	UserID uuid.UUID
	Tier   int16
}

type RecomputeTierProgressForTierRow struct {
	Tier            int16
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
}

// Single-tier variant of RecomputeTierProgress, for the per-answer /
// per-introduction transactional recompute (architecture §4.2/§5.5: "only the
// item's tier needs recompute").
func (q *Queries) RecomputeTierProgressForTier(ctx context.Context, arg RecomputeTierProgressForTierParams) (RecomputeTierProgressForTierRow, error) {
	row := q.db.QueryRow(ctx, recomputeTierProgressForTier, arg.UserID, arg.Tier)
	var i RecomputeTierProgressForTierRow
	err := row.Scan(
		&i.Tier,
		&i.TotalItems,
		&i.IntroducedItems,
		&i.GoodShapeItems,
	)
	return i, err
}

const recomputeTopicProgress = `-- name: RecomputeTopicProgress :one
WITH target AS (SELECT path FROM topic_paths WHERE topic_paths.id = $2)
SELECT
  count(*)::int AS total_items,
  count(*) FILTER (WHERE ui.lifecycle IS NOT NULL AND ui.lifecycle <> 0)::int AS introduced_items,
  count(*) FILTER (WHERE ui.lifecycle = 3
                      OR (ui.state = 2 AND ui.stability >= 21))::int AS good_shape_items
FROM items i
JOIN topic_paths tp ON tp.id = i.topic_id
CROSS JOIN target
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = $1
WHERE tp.path = target.path OR tp.path LIKE target.path || '/%'
`

type RecomputeTopicProgressParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type RecomputeTopicProgressRow struct {
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
}

// internal/study.TopicService, architecture §5.2 TopicRow: aggregate
// progress across an ENTIRE topic subtree (the topic itself plus every
// descendant, via the topic_paths recursive view) for one user — a
// container topic like "languages" rolls up every quizzable topic beneath
// it (e.g. special-characters, guess-the-language/*, common-words) into one
// total/introduced/good-shape line. Always returns exactly one row (zeros
// when the subtree has no items).
func (q *Queries) RecomputeTopicProgress(ctx context.Context, arg RecomputeTopicProgressParams) (RecomputeTopicProgressRow, error) {
	row := q.db.QueryRow(ctx, recomputeTopicProgress, arg.UserID, arg.ID)
	var i RecomputeTopicProgressRow
	err := row.Scan(&i.TotalItems, &i.IntroducedItems, &i.GoodShapeItems)
	return i, err
}

const recomputeTopicTierBreakdown = `-- name: RecomputeTopicTierBreakdown :many
SELECT it.tier,
       count(*)::int AS total_items,
       count(*) FILTER (WHERE ui.lifecycle IS NOT NULL AND ui.lifecycle <> 0)::int AS introduced_items,
       count(*) FILTER (WHERE ui.lifecycle = 3
                           OR (ui.state = 2 AND ui.stability >= 21))::int AS good_shape_items
FROM items i
JOIN item_tiers it ON it.item_id = i.id
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = $1
WHERE i.topic_id = $2
GROUP BY it.tier
ORDER BY it.tier
`

type RecomputeTopicTierBreakdownParams struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
}

type RecomputeTopicTierBreakdownRow struct {
	Tier            int16
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
}

// internal/study.TopicService, architecture §5.2 TierRow: per-tier
// progress within ONE quizzable topic's OWN items (non-recursive — a
// quizzable topic holds items directly, never a mix of items and child
// topics), for one user.
func (q *Queries) RecomputeTopicTierBreakdown(ctx context.Context, arg RecomputeTopicTierBreakdownParams) ([]RecomputeTopicTierBreakdownRow, error) {
	rows, err := q.db.Query(ctx, recomputeTopicTierBreakdown, arg.UserID, arg.TopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecomputeTopicTierBreakdownRow{}
	for rows.Next() {
		var i RecomputeTopicTierBreakdownRow
		if err := rows.Scan(
			&i.Tier,
			&i.TotalItems,
			&i.IntroducedItems,
			&i.GoodShapeItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTierProgress = `-- name: UpsertTierProgress :exec
INSERT INTO user_tier_progress (user_id, tier, total_items, introduced_items, good_shape_items, complete)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, tier) DO UPDATE SET
  total_items = EXCLUDED.total_items,
  introduced_items = EXCLUDED.introduced_items,
  good_shape_items = EXCLUDED.good_shape_items,
  complete = EXCLUDED.complete,
  updated_at = now()
`

type UpsertTierProgressParams struct {
	UserID          uuid.UUID
	Tier            int16
	TotalItems      int32
	IntroducedItems int32
	GoodShapeItems  int32
	Complete        bool
}

func (q *Queries) UpsertTierProgress(ctx context.Context, arg UpsertTierProgressParams) error {
	_, err := q.db.Exec(ctx, upsertTierProgress,
		arg.UserID,
		arg.Tier,
		arg.TotalItems,
		arg.IntroducedItems,
		arg.GoodShapeItems,
		arg.Complete,
	)
	return err
}
