// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubtreeQuizzableTopicCounts = `-- name: GetSubtreeQuizzableTopicCounts :one
WITH target AS (SELECT path FROM topic_paths WHERE topic_paths.id = $2)
SELECT
  count(*)::int AS total,
  count(*) FILTER (WHERE COALESCE(ut.enabled, true))::int AS enabled
FROM topics t
JOIN topic_paths tp ON tp.id = t.id
CROSS JOIN target
LEFT JOIN user_topics ut ON ut.topic_id = t.id AND ut.user_id = $1
WHERE t.is_quizzable
  AND (tp.path = target.path OR tp.path LIKE target.path || '/%')
`

type GetSubtreeQuizzableTopicCountsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetSubtreeQuizzableTopicCountsRow struct {
	Total   int32
	Enabled int32
}

// internal/study.TopicService, the /topics group-level "Turn group off/on"
// toggle (a container's drilled-in view): aggregate enabled-vs-total counts
// across every QUIZZABLE topic in topicID's subtree (itself + descendants,
// via the topic_paths recursive view) for one user, in a single set-based
// query — feeds the button's tri-state read (all on / all off / mixed)
// without an N+1 per-topic walk.
func (q *Queries) GetSubtreeQuizzableTopicCounts(ctx context.Context, arg GetSubtreeQuizzableTopicCountsParams) (GetSubtreeQuizzableTopicCountsRow, error) {
	row := q.db.QueryRow(ctx, getSubtreeQuizzableTopicCounts, arg.UserID, arg.ID)
	var i GetSubtreeQuizzableTopicCountsRow
	err := row.Scan(&i.Total, &i.Enabled)
	return i, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at FROM topics WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Position,
		&i.BaseTier,
		&i.QuizKind,
		&i.ExerciseModes,
		&i.IsQuizzable,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicByPath = `-- name: GetTopicByPath :one
SELECT t.id, t.parent_id, t.slug, t.name, t.position, t.base_tier, t.quiz_kind, t.exercise_modes, t.is_quizzable, t.config, t.created_at
FROM topics t
JOIN topic_paths tp ON tp.id = t.id
WHERE tp.path = $1
`

// Path-walk helper: resolve a topic by its full slash-joined slug path (e.g.
// "languages/special-characters"), via topic_paths.
func (q *Queries) GetTopicByPath(ctx context.Context, path string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByPath, path)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Position,
		&i.BaseTier,
		&i.QuizKind,
		&i.ExerciseModes,
		&i.IsQuizzable,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicPath = `-- name: GetTopicPath :one
SELECT id, path, depth FROM topic_paths WHERE id = $1
`

// Path-walk helper: slash-joined slug path + depth from the recursive
// topic_paths view, for one topic id.
func (q *Queries) GetTopicPath(ctx context.Context, id uuid.UUID) (TopicPath, error) {
	row := q.db.QueryRow(ctx, getTopicPath, id)
	var i TopicPath
	err := row.Scan(&i.ID, &i.Path, &i.Depth)
	return i, err
}

const getUserTopicEnabled = `-- name: GetUserTopicEnabled :one
SELECT COALESCE(ut.enabled, true) AS enabled
FROM topics t
LEFT JOIN user_topics ut ON ut.topic_id = t.id AND ut.user_id = $1
WHERE t.id = $2
`

type GetUserTopicEnabledParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// internal/study.Service, the /topics enable/disable toggle: a single
// topic's enabled flag for a user (default-on when no user_topics row
// exists), for rendering the toggle's current state without listing every
// topic (ListUserTopics).
func (q *Queries) GetUserTopicEnabled(ctx context.Context, arg GetUserTopicEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, getUserTopicEnabled, arg.UserID, arg.ID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listAllTopics = `-- name: ListAllTopics :many
SELECT id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at FROM topics ORDER BY position, slug
`

func (q *Queries) ListAllTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.BaseTier,
			&i.QuizKind,
			&i.ExerciseModes,
			&i.IsQuizzable,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildTopics = `-- name: ListChildTopics :many
SELECT id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at FROM topics WHERE parent_id = $1 ORDER BY position, slug
`

func (q *Queries) ListChildTopics(ctx context.Context, parentID *uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listChildTopics, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.BaseTier,
			&i.QuizKind,
			&i.ExerciseModes,
			&i.IsQuizzable,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootTopics = `-- name: ListRootTopics :many
SELECT id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at FROM topics WHERE parent_id IS NULL ORDER BY position, slug
`

func (q *Queries) ListRootTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listRootTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.BaseTier,
			&i.QuizKind,
			&i.ExerciseModes,
			&i.IsQuizzable,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicPaths = `-- name: ListTopicPaths :many
SELECT id, path, depth FROM topic_paths ORDER BY path
`

func (q *Queries) ListTopicPaths(ctx context.Context) ([]TopicPath, error) {
	rows, err := q.db.Query(ctx, listTopicPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopicPath{}
	for rows.Next() {
		var i TopicPath
		if err := rows.Scan(&i.ID, &i.Path, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTopics = `-- name: ListUserTopics :many
SELECT t.id, t.parent_id, t.slug, t.name, t.position, t.base_tier, t.quiz_kind,
       t.exercise_modes, t.is_quizzable, t.config, t.created_at,
       COALESCE(ut.enabled, true) AS enabled
FROM topics t
LEFT JOIN user_topics ut ON ut.topic_id = t.id AND ut.user_id = $1
ORDER BY t.position, t.slug
`

type ListUserTopicsRow struct {
	ID            uuid.UUID
	ParentID      *uuid.UUID
	Slug          string
	Name          string
	Position      int32
	BaseTier      int16
	QuizKind      string
	ExerciseModes []string
	IsQuizzable   bool
	Config        []byte
	CreatedAt     pgtype.Timestamptz
	Enabled       bool
}

// Every topic with the user's enabled flag (default-on when no row exists,
// per architecture §2.10 / §9 open question 5).
func (q *Queries) ListUserTopics(ctx context.Context, userID uuid.UUID) ([]ListUserTopicsRow, error) {
	rows, err := q.db.Query(ctx, listUserTopics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTopicsRow{}
	for rows.Next() {
		var i ListUserTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.Name,
			&i.Position,
			&i.BaseTier,
			&i.QuizKind,
			&i.ExerciseModes,
			&i.IsQuizzable,
			&i.Config,
			&i.CreatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reparentTopic = `-- name: ReparentTopic :exec
UPDATE topics SET parent_id = $2 WHERE id = $1
`

type ReparentTopicParams struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
}

// Re-parenting is a single-row UPDATE (architecture §2.1) — the tree is tiny,
// so the topic_paths recursive view stays cheap even after this.
func (q *Queries) ReparentTopic(ctx context.Context, arg ReparentTopicParams) error {
	_, err := q.db.Exec(ctx, reparentTopic, arg.ID, arg.ParentID)
	return err
}

const setSubtreeTopicsEnabled = `-- name: SetSubtreeTopicsEnabled :exec
WITH target AS (SELECT path FROM topic_paths WHERE topic_paths.id = $2)
INSERT INTO user_topics (user_id, topic_id, enabled)
SELECT $1, t.id, $3
FROM topics t
JOIN topic_paths tp ON tp.id = t.id
CROSS JOIN target
WHERE t.is_quizzable
  AND (tp.path = target.path OR tp.path LIKE target.path || '/%')
ON CONFLICT (user_id, topic_id)
DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetSubtreeTopicsEnabledParams struct {
	UserID  uuid.UUID
	ID      uuid.UUID
	Enabled bool
}

// internal/study.TopicService.SetSubtreeEnabled: the group-level toggle's
// write side — upserts user_topics.enabled for every QUIZZABLE topic in
// topicID's subtree (itself + descendants, via topic_paths) in one
// set-based statement, idempotent like SetUserTopicEnabled above.
func (q *Queries) SetSubtreeTopicsEnabled(ctx context.Context, arg SetSubtreeTopicsEnabledParams) error {
	_, err := q.db.Exec(ctx, setSubtreeTopicsEnabled, arg.UserID, arg.ID, arg.Enabled)
	return err
}

const setUserTopicEnabled = `-- name: SetUserTopicEnabled :exec

INSERT INTO user_topics (user_id, topic_id, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, topic_id)
DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetUserTopicEnabledParams struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
	Enabled bool
}

// ── user_topics (per-user topic opt-in/out, §2.10) ─────────────────────────
func (q *Queries) SetUserTopicEnabled(ctx context.Context, arg SetUserTopicEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserTopicEnabled, arg.UserID, arg.TopicID, arg.Enabled)
	return err
}

const upsertChildTopic = `-- name: UpsertChildTopic :one
INSERT INTO topics (parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (parent_id, slug) WHERE parent_id IS NOT NULL
DO UPDATE SET
  name = EXCLUDED.name,
  position = EXCLUDED.position,
  base_tier = EXCLUDED.base_tier,
  quiz_kind = EXCLUDED.quiz_kind,
  exercise_modes = EXCLUDED.exercise_modes,
  is_quizzable = EXCLUDED.is_quizzable,
  config = EXCLUDED.config
RETURNING id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at
`

type UpsertChildTopicParams struct {
	ParentID      *uuid.UUID
	Slug          string
	Name          string
	Position      int32
	BaseTier      int16
	QuizKind      string
	ExerciseModes []string
	IsQuizzable   bool
	Config        []byte
}

// Upsert a child topic (parent_id NOT NULL), keyed by the topics_sibling_slug
// partial unique index.
func (q *Queries) UpsertChildTopic(ctx context.Context, arg UpsertChildTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, upsertChildTopic,
		arg.ParentID,
		arg.Slug,
		arg.Name,
		arg.Position,
		arg.BaseTier,
		arg.QuizKind,
		arg.ExerciseModes,
		arg.IsQuizzable,
		arg.Config,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Position,
		&i.BaseTier,
		&i.QuizKind,
		&i.ExerciseModes,
		&i.IsQuizzable,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRootTopic = `-- name: UpsertRootTopic :one
INSERT INTO topics (slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (slug) WHERE parent_id IS NULL
DO UPDATE SET
  name = EXCLUDED.name,
  position = EXCLUDED.position,
  base_tier = EXCLUDED.base_tier,
  quiz_kind = EXCLUDED.quiz_kind,
  exercise_modes = EXCLUDED.exercise_modes,
  is_quizzable = EXCLUDED.is_quizzable,
  config = EXCLUDED.config
RETURNING id, parent_id, slug, name, position, base_tier, quiz_kind, exercise_modes, is_quizzable, config, created_at
`

type UpsertRootTopicParams struct {
	Slug          string
	Name          string
	Position      int32
	BaseTier      int16
	QuizKind      string
	ExerciseModes []string
	IsQuizzable   bool
	Config        []byte
}

// Upsert a root topic (parent_id IS NULL), keyed by the topics_root_slug
// partial unique index.
func (q *Queries) UpsertRootTopic(ctx context.Context, arg UpsertRootTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, upsertRootTopic,
		arg.Slug,
		arg.Name,
		arg.Position,
		arg.BaseTier,
		arg.QuizKind,
		arg.ExerciseModes,
		arg.IsQuizzable,
		arg.Config,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.Name,
		&i.Position,
		&i.BaseTier,
		&i.QuizKind,
		&i.ExerciseModes,
		&i.IsQuizzable,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}
