// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDueUserItems = `-- name: CountDueUserItems :one
SELECT count(*) FROM user_items ui
JOIN items i ON i.id = ui.item_id
JOIN users u ON u.id = $1
WHERE ui.user_id = $1 AND ui.lifecycle IN (1, 2) AND ui.due <= $2
  AND (NOT u.gg_only OR i.gg_relevant)
`

type CountDueUserItemsParams struct {
	UserID uuid.UUID
	Due    pgtype.Timestamptz
}

// internal/study.Service.DueCount / the reminder loop's due count:
// Introduced/Reviewing cards due at or before now. GeoGuessr-only filtered
// (see ListDueUserItems).
func (q *Queries) CountDueUserItems(ctx context.Context, arg CountDueUserItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDueUserItems, arg.UserID, arg.Due)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIntroducedItems = `-- name: CountIntroducedItems :one
SELECT count(*) FROM user_items ui
JOIN items i ON i.id = ui.item_id
JOIN users u ON u.id = $1
WHERE ui.user_id = $1 AND ui.lifecycle IN (1, 2, 3)
  AND (NOT u.gg_only OR i.gg_relevant)
`

// internal/study.Service.Stats, "introduced" count: items that have
// left lifecycle=new (Introduced, Reviewing, or Known). GeoGuessr-only
// filtered (see ListDueUserItems).
func (q *Queries) CountIntroducedItems(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIntroducedItems, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnownItems = `-- name: CountKnownItems :one
SELECT count(*) FROM user_items ui
JOIN items i ON i.id = ui.item_id
JOIN users u ON u.id = $1
WHERE ui.user_id = $1 AND ui.lifecycle = 3
  AND (NOT u.gg_only OR i.gg_relevant)
`

// internal/study.Service.Stats, "known" count: items marked known via
// the "I know this" intro outcome. GeoGuessr-only filtered (see
// ListDueUserItems).
func (q *Queries) CountKnownItems(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKnownItems, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserItem = `-- name: GetUserItem :one
SELECT user_id, item_id, lifecycle, due, stability, difficulty, reps, lapses, state, last_review, introduced_at, known_at, updated_at FROM user_items WHERE user_id = $1 AND item_id = $2
`

type GetUserItemParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) GetUserItem(ctx context.Context, arg GetUserItemParams) (UserItem, error) {
	row := q.db.QueryRow(ctx, getUserItem, arg.UserID, arg.ItemID)
	var i UserItem
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.Lifecycle,
		&i.Due,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.LastReview,
		&i.IntroducedAt,
		&i.KnownAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidateIntroItems = `-- name: ListCandidateIntroItems :many
SELECT i.id AS item_id, i.topic_id, i.key, i.label, it.tier
FROM items i
JOIN item_tiers it ON it.item_id = i.id
JOIN topics t ON t.id = i.topic_id
JOIN users u ON u.id = $1
LEFT JOIN user_items ui ON ui.item_id = i.id AND ui.user_id = $1
WHERE i.active = true
  AND (ui.item_id IS NULL OR ui.lifecycle = 0)
  AND it.tier = ANY($2::smallint[])
  AND (NOT u.gg_only OR i.gg_relevant)
ORDER BY it.tier, t.position, i.position
`

type ListCandidateIntroItemsParams struct {
	UserID uuid.UUID
	Tiers  []int16
}

type ListCandidateIntroItemsRow struct {
	ItemID  uuid.UUID
	TopicID uuid.UUID
	Key     string
	Label   string
	Tier    int16
}

// Candidate items for the introduction queue: active, tier-unlocked
// (parameterized allowed-tiers array), and either no user_items row yet or
// still lifecycle=new. Ordered tier, then topic position, then item position
// — the app-supplied priority order engram.NextIntroductions preserves.
// GeoGuessr-only filtered (see ListDueUserItems): non-coverage items are
// never introduced while the user's gg_only is set.
func (q *Queries) ListCandidateIntroItems(ctx context.Context, arg ListCandidateIntroItemsParams) ([]ListCandidateIntroItemsRow, error) {
	rows, err := q.db.Query(ctx, listCandidateIntroItems, arg.UserID, arg.Tiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidateIntroItemsRow{}
	for rows.Next() {
		var i ListCandidateIntroItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.TopicID,
			&i.Key,
			&i.Label,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueUserItems = `-- name: ListDueUserItems :many
SELECT ui.user_id, ui.item_id, ui.lifecycle, ui.due, ui.stability, ui.difficulty,
       ui.reps, ui.lapses, ui.state, ui.last_review, ui.introduced_at, ui.known_at,
       ui.updated_at, i.topic_id, i.key, i.label
FROM user_items ui
JOIN items i ON i.id = ui.item_id
JOIN users u ON u.id = $1
WHERE ui.user_id = $1 AND ui.lifecycle IN (1, 2) AND ui.due <= $2
  AND (NOT u.gg_only OR i.gg_relevant)
ORDER BY ui.due
`

type ListDueUserItemsParams struct {
	UserID uuid.UUID
	Due    pgtype.Timestamptz
}

type ListDueUserItemsRow struct {
	UserID       uuid.UUID
	ItemID       uuid.UUID
	Lifecycle    int16
	Due          pgtype.Timestamptz
	Stability    float64
	Difficulty   float64
	Reps         int32
	Lapses       int32
	State        int16
	LastReview   pgtype.Timestamptz
	IntroducedAt pgtype.Timestamptz
	KnownAt      pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	TopicID      uuid.UUID
	Key          string
	Label        string
}

// Due Introduced/Reviewing cards (engram.NextReview candidate set) joined
// with their item for topic/key/label context. GeoGuessr-only filter: joins
// the owning user and drops non-coverage items when users.gg_only is set
// (the predicate is a no-op when it isn't) — no extra parameter, since
// user_id ($1) already identifies the user whose flag governs the filter.
func (q *Queries) ListDueUserItems(ctx context.Context, arg ListDueUserItemsParams) ([]ListDueUserItemsRow, error) {
	rows, err := q.db.Query(ctx, listDueUserItems, arg.UserID, arg.Due)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueUserItemsRow{}
	for rows.Next() {
		var i ListDueUserItemsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Lifecycle,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IntroducedAt,
			&i.KnownAt,
			&i.UpdatedAt,
			&i.TopicID,
			&i.Key,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserItemCardsInFSRS = `-- name: ListUserItemCardsInFSRS :many
SELECT ui.user_id, ui.item_id, ui.lifecycle, ui.due, ui.stability, ui.difficulty, ui.reps, ui.lapses, ui.state, ui.last_review, ui.introduced_at, ui.known_at, ui.updated_at FROM user_items ui
JOIN items i ON i.id = ui.item_id
JOIN users u ON u.id = $1
WHERE ui.user_id = $1 AND ui.lifecycle IN (1, 2)
  AND (NOT u.gg_only OR i.gg_relevant)
`

// internal/study.Service.Stats' DueForecast input: every Introduced/
// Reviewing card for a user — replaces ListCardsForUser for the item-based review
// path. Known/new rows are excluded: they carry a zeroed/absent due date
// that would otherwise skew engram.DueForecast's "due today" bucket.
// GeoGuessr-only filtered (see ListDueUserItems).
func (q *Queries) ListUserItemCardsInFSRS(ctx context.Context, id uuid.UUID) ([]UserItem, error) {
	rows, err := q.db.Query(ctx, listUserItemCardsInFSRS, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserItem{}
	for rows.Next() {
		var i UserItem
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Lifecycle,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IntroducedAt,
			&i.KnownAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserItemsByLifecycle = `-- name: ListUserItemsByLifecycle :many
SELECT user_id, item_id, lifecycle, due, stability, difficulty, reps, lapses, state, last_review, introduced_at, known_at, updated_at FROM user_items WHERE user_id = $1 AND lifecycle = $2 ORDER BY updated_at
`

type ListUserItemsByLifecycleParams struct {
	UserID    uuid.UUID
	Lifecycle int16
}

func (q *Queries) ListUserItemsByLifecycle(ctx context.Context, arg ListUserItemsByLifecycleParams) ([]UserItem, error) {
	rows, err := q.db.Query(ctx, listUserItemsByLifecycle, arg.UserID, arg.Lifecycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserItem{}
	for rows.Next() {
		var i UserItem
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Lifecycle,
			&i.Due,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.LastReview,
			&i.IntroducedAt,
			&i.KnownAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putUserItem = `-- name: PutUserItem :exec
INSERT INTO user_items (
  user_id, item_id, lifecycle, due, stability, difficulty, reps, lapses,
  state, last_review, introduced_at, known_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (user_id, item_id)
DO UPDATE SET
  lifecycle = EXCLUDED.lifecycle,
  due = EXCLUDED.due,
  stability = EXCLUDED.stability,
  difficulty = EXCLUDED.difficulty,
  reps = EXCLUDED.reps,
  lapses = EXCLUDED.lapses,
  state = EXCLUDED.state,
  last_review = EXCLUDED.last_review,
  introduced_at = EXCLUDED.introduced_at,
  known_at = EXCLUDED.known_at,
  updated_at = now()
`

type PutUserItemParams struct {
	UserID       uuid.UUID
	ItemID       uuid.UUID
	Lifecycle    int16
	Due          pgtype.Timestamptz
	Stability    float64
	Difficulty   float64
	Reps         int32
	Lapses       int32
	State        int16
	LastReview   pgtype.Timestamptz
	IntroducedAt pgtype.Timestamptz
	KnownAt      pgtype.Timestamptz
}

// Upsert the lifecycle + FSRS card state for one user+item (engram.Lifecycle
// and engram.CardState, architecture §2.3).
func (q *Queries) PutUserItem(ctx context.Context, arg PutUserItemParams) error {
	_, err := q.db.Exec(ctx, putUserItem,
		arg.UserID,
		arg.ItemID,
		arg.Lifecycle,
		arg.Due,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.State,
		arg.LastReview,
		arg.IntroducedAt,
		arg.KnownAt,
	)
	return err
}
