// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, username, daily_new_cap, reminders_enabled, timezone, created_at, label_style, reminder_hour, follow_up_enabled, follow_up_delay_min, daily_intro_cap FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DailyNewCap,
		&i.RemindersEnabled,
		&i.Timezone,
		&i.CreatedAt,
		&i.LabelStyle,
		&i.ReminderHour,
		&i.FollowUpEnabled,
		&i.FollowUpDelayMin,
		&i.DailyIntroCap,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, username, daily_new_cap, reminders_enabled, timezone, created_at, label_style, reminder_hour, follow_up_enabled, follow_up_delay_min, daily_intro_cap FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DailyNewCap,
		&i.RemindersEnabled,
		&i.Timezone,
		&i.CreatedAt,
		&i.LabelStyle,
		&i.ReminderHour,
		&i.FollowUpEnabled,
		&i.FollowUpDelayMin,
		&i.DailyIntroCap,
	)
	return i, err
}

const setDailyCap = `-- name: SetDailyCap :exec
UPDATE users SET daily_new_cap = $2 WHERE id = $1
`

type SetDailyCapParams struct {
	ID          uuid.UUID
	DailyNewCap int32
}

func (q *Queries) SetDailyCap(ctx context.Context, arg SetDailyCapParams) error {
	_, err := q.db.Exec(ctx, setDailyCap, arg.ID, arg.DailyNewCap)
	return err
}

const setFollowUpDelay = `-- name: SetFollowUpDelay :exec
UPDATE users SET follow_up_delay_min = $2 WHERE id = $1
`

type SetFollowUpDelayParams struct {
	ID               uuid.UUID
	FollowUpDelayMin int32
}

func (q *Queries) SetFollowUpDelay(ctx context.Context, arg SetFollowUpDelayParams) error {
	_, err := q.db.Exec(ctx, setFollowUpDelay, arg.ID, arg.FollowUpDelayMin)
	return err
}

const setFollowUpEnabled = `-- name: SetFollowUpEnabled :exec
UPDATE users SET follow_up_enabled = $2 WHERE id = $1
`

type SetFollowUpEnabledParams struct {
	ID              uuid.UUID
	FollowUpEnabled bool
}

func (q *Queries) SetFollowUpEnabled(ctx context.Context, arg SetFollowUpEnabledParams) error {
	_, err := q.db.Exec(ctx, setFollowUpEnabled, arg.ID, arg.FollowUpEnabled)
	return err
}

const setLabelStyle = `-- name: SetLabelStyle :exec
UPDATE users SET label_style = $2 WHERE id = $1
`

type SetLabelStyleParams struct {
	ID         uuid.UUID
	LabelStyle string
}

func (q *Queries) SetLabelStyle(ctx context.Context, arg SetLabelStyleParams) error {
	_, err := q.db.Exec(ctx, setLabelStyle, arg.ID, arg.LabelStyle)
	return err
}

const setReminderHour = `-- name: SetReminderHour :exec
UPDATE users SET reminder_hour = $2 WHERE id = $1
`

type SetReminderHourParams struct {
	ID           uuid.UUID
	ReminderHour int32
}

func (q *Queries) SetReminderHour(ctx context.Context, arg SetReminderHourParams) error {
	_, err := q.db.Exec(ctx, setReminderHour, arg.ID, arg.ReminderHour)
	return err
}

const setReminders = `-- name: SetReminders :exec
UPDATE users SET reminders_enabled = $2 WHERE id = $1
`

type SetRemindersParams struct {
	ID               uuid.UUID
	RemindersEnabled bool
}

func (q *Queries) SetReminders(ctx context.Context, arg SetRemindersParams) error {
	_, err := q.db.Exec(ctx, setReminders, arg.ID, arg.RemindersEnabled)
	return err
}

const setTimezone = `-- name: SetTimezone :exec
UPDATE users SET timezone = $2 WHERE id = $1
`

type SetTimezoneParams struct {
	ID       uuid.UUID
	Timezone string
}

func (q *Queries) SetTimezone(ctx context.Context, arg SetTimezoneParams) error {
	_, err := q.db.Exec(ctx, setTimezone, arg.ID, arg.Timezone)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (telegram_id, username)
VALUES ($1, $2)
ON CONFLICT (telegram_id)
DO UPDATE SET username = EXCLUDED.username
RETURNING id, telegram_id, username, daily_new_cap, reminders_enabled, timezone, created_at, label_style, reminder_hour, follow_up_enabled, follow_up_delay_min, daily_intro_cap
`

type UpsertUserParams struct {
	TelegramID int64
	Username   pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.TelegramID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Username,
		&i.DailyNewCap,
		&i.RemindersEnabled,
		&i.Timezone,
		&i.CreatedAt,
		&i.LabelStyle,
		&i.ReminderHour,
		&i.FollowUpEnabled,
		&i.FollowUpDelayMin,
		&i.DailyIntroCap,
	)
	return i, err
}

const usersWithReminders = `-- name: UsersWithReminders :many
SELECT id, telegram_id, username, daily_new_cap, reminders_enabled, timezone, created_at, label_style, reminder_hour, follow_up_enabled, follow_up_delay_min, daily_intro_cap FROM users WHERE reminders_enabled = true ORDER BY created_at
`

func (q *Queries) UsersWithReminders(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, usersWithReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Username,
			&i.DailyNewCap,
			&i.RemindersEnabled,
			&i.Timezone,
			&i.CreatedAt,
			&i.LabelStyle,
			&i.ReminderHour,
			&i.FollowUpEnabled,
			&i.FollowUpDelayMin,
			&i.DailyIntroCap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
